
Logic - Worksheet 1 {data-navmenu="Exercises"}
==================================

Column {.tabset}
-----------------------------



### Work Sheet 1


#### Question 1

Let $n \in \{1,2,3,4,5,6,7, 8 ,9\}$ and let $p,q$ be the following propositions concerning the integer $n$.


[p]: $n$ is even
[q]: $n < 5$.


Find the values of n for which each of the following compound statements is
true.

[(i)] $\neg p$
[(ii)] $p \wedge q$
[(iii)] $\neg p \vee q$
[(iv)] $ p \otimes q$.


#### Question 2

Let p and q be propositions.

[(i)]  Construct the truth table for $p \rightarrow q$. 
[(ii)] Use truth tables to prove that $\neg q \rightarrow \neg p$ = $p \rightarrow q$. 

[(c)] Let $p$, $q$ be the following propositions:

[p] : this apple is red, 
[q] : this apple is ripe. 


Express the following statements in words as simply as you can. 

[(i)] $p \rightarrow q$ 
[(ii)] $p \wedge \neg q$.

------------------------------------
<p>

#### Question 3 

Let $S = \{10,11,12,13,14,15,16,17,18,19\}$ and let p, q be the following propositions concerning the integer $n \in S$.


*  $p$: $n$ is a multiple of two. (i.,18e. $\{10,12,14,16,18\}$)
*  $q$: $n$ is a multiple of three. {i.e. $\{12,15,18\}$}


For each of the following compound statements find the sets of values $n$ for which it is true. 


*  $p \vee q$ : (p or q :  10 12 14 15 16 18) 
*  $p \wedge q$: (p and q: 12 18)
*  $ \neg p \oplus q$: (not-p or q, but not both)

*  $\neg p $ not-p = $\{ 11 13 15 17 19\}$
*  $\neg p \vee q$ not-p or q $\{11 12 13 15 17 18 19\}$
*  $\neg p \wedge q$ not-p and q $\{15\} $
*  $ \neg p \oplus q$ = $\{11, 12, 13, 17, 18, 19\}$




----------------------------------------------------
<p>



### Conditional Connectives

#### Question 4

Write the contrapositive of each of the following statements:


*  If n= 12, then n is divisible by 3.
*  If n=5, then n is positive.
*  If the quadrilateral is square, then four sides are equal.


#### Solutions

*  If n is not divisible by 3, then n is not equal to 12.
*  If n is not positive, then n is not equal to 5.
*  If the four sides are not equal, then the quadrilateral is not a square.


Let $n \in \{1,2,3,4,5,6,7, 8 ,9\}$ and let $p,q$ be the following propositions concerning the integer $n$.


* $p$: $n$ is even
* $q$: $n < 5$.


Find the values of n for which each of the following compound statements is
true.


a.  $\neg p$
b.  $p \wedge q$
c. $\neg p \vee q$
d. $ p \otimes q$.

---------------------------------

#### Exercise 

Let $n = \{1, 2,3,4, 5,6,7, 8, 9\}$ and let $p$ and  $q$ be the following propositions concerning the integer $n$.

* p: n is even, 
* q: $n\geq 5$.

By drawing up the appropriate truth table ï¬nd the truth set for each of the
propositions $p \vee \neg q$ and $ \neg q \rightarrow p$

---------------------------------

#### Exercise 
Let p, q be the following propositions:

$p$ : this apple is red, 
$q$ : this apple is ripe.


Express the following statements in words as simply as you can:

a.  $p \rightarrow q$
b.  $p \wedge \neg q$.


 
Express the following statements symbolically:

c. This apple is neither red nor ripe.
d. If this apple is not red it is not ripe.


---------------------------------

#### Question

Let p and q be propositions.

a.   Construct the truth table for $p \rightarrow q$. 
b.  Use truth tables to prove that $\neg q \rightarrow \neg p$ = $p \rightarrow q$. 




Truth Table - Worksheet 2 {data-navmenu="Exercises"}
==================================

Column {.tabset}
-----------------------------



### Work Sheet 3 -  Truth Table Questions


#### {Section 3 Logic}

\begin{center}
\begin{tabular}{|c|c|c|c|c|}
\hline
p & q & $p \vee q$ & $q \wedge p$ & $p \otimes q$ \\
\hline
0 & 0 & 0 & 0 & 0 \\
0 & 1 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 \\
1 & 1 & 1 & 1 & 0\\
\hline
\end{tabular}
\end{center}


---------------------------------------------------------

#### {Conditional Connectives}

Construct the truth table for the proposition $p \rightarrow q$.

\[
\begin{table}{|c|c|c|c|}
\hline
p & q & $p \rightarrow q$ & $q \rightarrow p$ \\
\hline
0 & 0 & 1& 1 \\
0 & 1 & 1 & 0 \\
1 & 0 & 0 & 1 \\
1 & 1 & 1 & 1 \\
\hline
\end{table}\]

Logic Networks - Worksheet 2 {data-navmenu="Exercises"}
==================================

Column {.tabset}
-----------------------------



### Work Sheet 3 - Logic Networks

#### Question 1

Construct a logic network that accepts as input p and q, which may independently have the value 0 or 1, and
gives as final input $\neg(p \wedge \not q)$ (i.e. $\equiv p \rightarrow q$).\\


#### Logic Gates

*  AND
*  OR
*  NOT




#### Question 2 

Construct a logic network that accepts as input p and q, which may independently have the value 0 or 1, and
gives as final input $(p \wedge  q) \vee \neg q$ (i.e. $\equiv p \rightarrow q$).


***Important*** Label each of the gates appropriately and label the diagram with a symblic expression for the output after each gate.


#### Question 3

Construct a logic network that accepts as input p and q, which may independently have the value 0 or 1, and
gives as final input $\neg(p \wedge \not q)$ (i.e. $\equiv p \rightarrow q$).

* Use \textbf{Truth Tables} to prove that the following statements are equivalent to one another.

\[(p \vee q) \wedge \neg q \qquad \equiv \qquad  p\wedge \neg q.\]

----------------

Construct a logic network that accepts as input $p$ and $q$, which may independently have the value 0 or 1, and
gives as final input $(p \wedge  q) \vee \neg q$ (i.e. $\equiv p \rightarrow q$).



***Important*** Label each of the gates appropriately and label the diagram with a symblic expression for the output after each gate.


