Matrices {data-navmenu="Matrices"}
=====================================

Column {.tabset}
-------------------------------------------------

### Introduction

In mathematics, a matrix (plural matrices ) is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns. 

Matrices are commonly written in box brackets.

An $m \times n$ (read ‘m by n’) matrix is an arrangement of numbers (or algebraic expressions ) in $m$ rows and $n$ columns. 

Each number in a given matrix is called an element or entry. A zero matrix has all its elements equal to zero.

* <a href= "https://youtube.com/watch?v=/z3Vfd_unDBE"> Basic Matrix Operations ( Discrete Mathematics )  </a>


* <a href= "https://youtube.com/watch?v=/cGJuRL0Az5I"> Matrix Multiplication ( Discrete Mathematics )  </a>



#### Matrices and Systems of Equations

* Dimensions of a Matrix
* Matrix Multiplication
* Matrix Calculations
* Systems of Equations
* Expression Systems of Equations as Matrices
* Augmented Matrices
* Guassian Elimination

### Matrix algebra 

* Writing a system of linear equations as a matrix equation
* The rules for when two matrices can be added and subtracted
* The rules for when two matrices can be multiplied
* Adding, subtracting and multiplying matrices of suitable sizes
* The identity matrices In and their properties
* Interpreting powers of the adiacency matrix of a graph/digraph



### Matrix Operations

#### Commutativity and Associativity
Matrices of the same size can be added or subtracted element by element. 

\[ A \times B \neq B \times A \]



### Matrix Multiplication

* Method for multiply a pair of $2\times2$ matrices.

\[ \left(
\begin{array}{cc}
a_1 & a_2 \\ 
b_1 & b_2
\end{array} \right)\left(
\begin{array}{cc}
c_1 & d_1 \\ 
c_2 & d_2
\end{array} \right) = \left(
\begin{array}{cc}
(a_1 \times c_1) + (a_2 \times c_2) & (a_1 \times d_1) + (a_2 \times d_2) \\ 
(b_1 \times c_1) + (b_2 \times c_2) & (b_1 \times d_1) + (b_2 \times d_2)
\end{array} \right) \]

#### Example

\[ \left(
\begin{array}{cc}
1 & 3 \\ 
0 & 2
\end{array} \right)\left(
\begin{array}{cc}
1 & 2 \\ 
4 & 1
\end{array} \right) = \left(
\begin{array}{cc}
(1 \times 1) + (3 \times 4) & (1 \times 2) + (3 \times 1) \\ 
(0 \times 4) + (2 \times 4) & (0 \times 2) + (2 \times 1)
\end{array} \right) = \left(
\begin{array}{cc}
14 & 5 \\ 
8 & 2
\end{array} \right) \]


### Determinants


The determinant helps us find the inverse of a matrix, tells us things about the matrix that are useful in systems of linear equations, calculus and more.

The symbol for determinant is two vertical lines either side: |A| means the determinant of the matrix A (exactly the same symbol as absolute value.)

In the case of a 2 × 2 matrix the determinant can be defined as

$${\displaystyle {\begin{aligned}|A|={\begin{vmatrix}a&b\\c&d\end{vmatrix}}=ad-bc.\end{aligned}}}$$
Similarly, for a 3 × 3 matrix A, its determinant is

$${\displaystyle {\begin{aligned}|A|={\begin{vmatrix}a&b&c\\d&e&f\\g&h&i\end{vmatrix}}&=a\,{\begin{vmatrix}e&f\\h&i\end{vmatrix}}-b\,{\begin{vmatrix}d&f\\g&i\end{vmatrix}}+c\,{\begin{vmatrix}d&e\\g&h\end{vmatrix}}\\[3pt]&=aei+bfg+cdh-ceg-bdi-afh.\end{aligned}}}$$

### Terminology


#### Order of a Matrix

Consider the following matrix $A$
\[A =  
\right(\begin{array}{ccc}
6 & 3 & 2 \\
4 & 7 & 5 \\
\end{array}\left)
\] 


* $A$ has 2 rows and 3 columns.
* We would say A is a $2 \times 3$ matrix.




#### Square Matrices

A square matrix is a matrix with the same 
number of rows and columns. An $n\times n$ matrix is known as a square matrix of order n. Any two square matrices of the same order can be added and multiplied. 


#### Diagonal and triangular matrices


If all entries of A below the main diagonal are zero, A is called an upper triangular matrix. Similarly if all entries of A above the main diagonal are zero, A is called a lower triangular matrix. If all entries outside the main diagonal are zero, A is called a diagonal matrix.




#### The Identity Matrix


The identity matrix or unit matrix of size n is the $n\times n$  square matrix with ones on the main diagonal and zeros elsewhere. It is denoted by $I_n$, or simply by I if the size is immaterial or can be trivially determined by the context. 

\[
I_{1}={\begin{bmatrix}1\end{bmatrix}},\ I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\ I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}},\ \cdots ,\ I_{n}={\begin{bmatrix}1&0&\cdots &0\\0&1&\cdots &0\\\vdots &\vdots &\ddots &\vdots \\0&0&\cdots &1\end{bmatrix}}
\]

* When A is a square matrix (i.e. $n\times n$), it is a property of matrix multiplication that
\[I_{N}A=AI_{n}=A.\,\]

* When A is $m\times n$, it is a property of matrix multiplication that
\[I_{m}A=AI_{n}=A.\,\]

* The Identity matrix itself is invertible, being its own inverse.

* The Identity matrix is symmetrix, which is to say, it is it's own tranpose.


\[ 
\right(\begin{array}{ccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{array}\left)
\] 


#### Tranpose of a Matrix

A ***symmetric*** matrix is a matrix that is identical to it's tranpose.




### Tutorials

Matrices Tutorial 1

* Question 1 <a href= "https://youtube.com/watch?v=/XCYf81OTDVc"> Here</a>
* Question 2 <a href= "https://youtube.com/watch?v=/z1aIiH4bE4k"> Here</a>
* Question 3  - Part 1 <a href= "https://youtube.com/watch?v=/FtyNlZIsiXg"> Here</a>
* Question 3  - Part 2 <a href= "https://youtube.com/watch?v=/Xwg6VB_ooHk"> Here</a>
* Question 4
* Question 5
* Question 6
* Question 7 <a href= "https://youtube.com/watch?v=/Jj_7KiXJb64"> Here</a>
* Question 8 <a href= "https://youtube.com/watch?v=/tdVrjFFq1A8"> Here</a>
