---
title: "Spanning Trees"
subtitle: "DiscreteMaths.github.io"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    font_size: 20pts
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

<style type="text/css">
  body{
  font-size: 20pt;
}
</style>

```{r eval=FALSE,include=FALSE}

# CT6 
# - ASI 2005 April Question B - 1
# - ASI 2006 April Question B - 1

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(knitr)
library(dplyr)
library(janitor)


```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent_inverse(
  #base_color = "#4169e1", #)(vvv#TREES
  #background_color = "#E6E6FA",  #TREE
  base_color = "black", #)(
  background_color = "#98a869",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "400", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

# Hexadecimal Numbers
## Worked Example: Converting to Base 10 (Example 2)
<br>
## Discrete Maths for Computer Science Students
<br><br><br><br>
### <tt>DiscreteMaths.github.io</tt>