---
title: "Discrete Mathematics"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


Discrete Mathematics {data-navmenu="Introduction"}
=====================================

Column 
--------------------

### Introduction

<p>



<p>

<h4>Programme and Abstracts</h4>
<p>
* Date: Saturday 29th February 2020
* Location: Strand Hotel Limerick 
* Times: 10.00am to 17:10pm approx



Number Systems {data-navmenu="Section 1"}
==============================================================

Column {.tabset}
-------------------------------------------------------------

### Real and Irrational Numbers

#### Real and Irrational Numbers

*  <a title="Number Sets" href="http://youtu.be/9NAmHx3pAxk" target="_blank">Number Sets</a>Natural Numbers, Integers, Rational Numbers and Real Numbers.
*  <a title="Irrational Numbers" href="http://youtu.be/lu7uhe903TY" target="_blank">Irrational Numbers</a>: Exercise involving irrational numbers.
*  <a title="Rational Numbers" href="http://youtu.be/WnXnVADCXuQ" target="_blank">Rational and Irrational Numbers</a>[4:16] (New Video)
*  <a title="Repeating Decimals" href="http://youtu.be/mhHAJOQQ8kM" target="_blank">Repeating Decimals</a>(video 1)
*  <a title="Repeating Decimal" href="http://youtu.be/99qV28WmzH4" target="_blank">Repeating Decimal </a>[3:37](Video 2)


<h5>Discrete Maths: Numbers</h5>


### Part 1. Number Bases

*  Numbers in Base 10
*  The binary system
*  Calculating in the binary system
*  The Hexadecimal system
*  Converting decimal integers into other bases


### Part 2. Rational Numbers

*  Factor, multiples and primes
*  Representing fractions
*  Decimal fractions
*  Fractions in bases other than 10


### Part 3. Real Numbers

*  Irrational numbers
*  Inequality symbols
*  Floating-point notation


* <a href="https://www.youtube.com/embed/9NAmHx3pAxk" >Number Sets: Natural Numbers, Integers, Rational Numbers and Real Numbers.</a>
* <a href="https://www.youtube.com/embed/lu7uhe903TY" >Irrational Numbers: Exercise involving irrational numbers.</a>
* <a href="https://www.youtube.com/embed/WnXnVADCXuQ" >Rational and Irrational Numbers</a>

* <a href="https://www.youtube.com/embed/mhHAJOQQ8kM" >Repeating Decimals</a>
* <a href="https://www.youtube.com/embed/99qV28WmzH4" >Repeating Decimals</a>
* <a href="https://www.youtube.com/embed/sIowD1XjFJ8" >Repeating Decimals</a>




Binary Numbers {data-navmenu="Section 1"}
==================================

* <a href="https://www.youtube.com/embed/Xj75KbggKMU">Binary Number Conversion</a>

* <a href="https://www.youtube.com/embed/xyo2UiDpND8"> Expressing Binary Numbers</a>

* <a href="https://www.youtube.com/embed/HDQ7PGYo5Y8"> Binary Addition</a>

* <a href="https://www.youtube.com/embed/Hz3PfnllV6I">Binary Addition</a>

* <a href="https://www.youtube.com/embed/cnv7scvjc7o"> Binary Addition </a>

* <a href="https://www.youtube.com/embed/dQMQMvU4GT0"> Binary Subtraction: using Borrowing Method</a>

* <a href="https://www.youtube.com/embed/iwzaZDdaT9g">Binary Numbers Adding Two Binary Numbers (Example) HD</a>
    
* <a href="https://www.youtube.com/embed/DTO3mS5D2lA">Binary Subtraction using "Two's Complement"</a>

* <a href="https://www.youtube.com/embed/Ai5F0KLyh2Q"> Left Shifting Technique for Binary Multiplication</a>

* <a href="https://www.youtube.com/embed/P_vd1vkafYk">  Binary Subtraction: using Twos Complement</a>
    
* <a href="https://www.youtube.com/embed/WfWHdWwITgk"> Binary Multiplication: using Left Shifting</a>

* <a href="https://www.youtube.com/embed/A08P9ZJsLOs"> Relations -Example</a>

* <a href="https://www.youtube.com/embed/-svSPXMGyfs "> Binary Multiplication ( Binary Numbers Tutorial Sheet)		</a>


Column {.tabset}
-----------------------------

Hexadecimal Numbers {data-navmenu="Section 1"}
==================================

Column {.tabset}
-----------------------------

### Hexadecimal Numbers

### Videos


* <a href="https://www.youtube.com/embed/-4uUCdDxsrU">Hexadecimal Number Conversion</a>
* <a href="https://www.youtube.com/embed/JvMNIkmszaU">Converting Hexadecimal Numbers With Fractions to Decimal Form</a>
* <a href="https://www.youtube.com/embed/ztxKt77mTFE">Converting Decimal Fractions to Hexadecimal</a>
* <a href="https://www.youtube.com/embed/ussn9qLHYrE">Hexadecimal and Binary Numbers</a>
* <a href="https://www.youtube.com/embed/d6_oOPZBdTY">Binary and Hexadecimal Arithmetic</a>
* <a href="https://www.youtube.com/embed/ztxKt77mTFE">Converting Decimal Fractions to Hexadecimal</a>
* <a href="https://www.youtube.com/embed/VSwZ-1mCEW0">Converting Hex to Binary</a>
* <a href="https://www.youtube.com/embed/UWbKK6Q8xlY">Adding Hexadecimal Numbers[6:38]</a>
* <a href="https://www.youtube.com/embed/Stt4nkIeaEc">Spreadsheet Commands[6:43] Checking your answers on a spreadsheet.</a>



Set Theory {data-navmenu="Section 2"}
====================================

Column {.tabset}
-------------------------------------------------------------

### Set Theory Operations

*  The Universal Set $\mathcal{U}$
*  Union
*  Intersection
*  Set Difference
*  Relative Difference





Logic {data-navmenu="Section 2"}
====================================

Column {.tabset}
-------------------------------

### Logic 

Propositions, The negations of a proposition, Compound Statements, Truth tables

* <a href = "https://www.youtube.com/embed/YK6tzrBYS14"> Logic 2003 Propositions</a>
* <a href = "https://www.youtube.com/embed/SNah7Lai_Lo"> Logic 2007 Propositions </a>
* <a href = "https://www.youtube.com/embed/qLP5fnux3RA"> Introduction to Truth Tables</a>

* <a href = "https://www.youtube.com/embed/qiO6sEmfkIc"> Proof using Truth Tables</a>
* <a href = "https://www.youtube.com/embed/Z9YVIP7v-Ik"> Proof using Truth Tables</a>
* <a href = "https://www.youtube.com/embed/4ZSgi6lmd_4"> Logic proof by truth table</a>

* <a href = "https://www.youtube.com/embed/U_VxV-3p7dU"> Logic 2007 Question 3 Truth Tables</a>
* <a href = "https://www.youtube.com/embed/FT9ocP-L6Mc"> Conditional Connectives :  p implies q </a>
* <a href = "https://www.youtube.com/embed/dnem1E71TI4"> Logic 2001 Implication Connective</a>

* <a href = "https://www.youtube.com/embed/s1f3nCOOzz8">  HERE </a>

### Truth Tables

* Introduction to Truth Tables

### Conditional Connectives

* Truth tables for condition connectives  
* The contrapositive

### Logic Networks

* <a href = "https://www.youtube.com/embed/DtkPULIOlWQ"> Logic Networks: (Example 1)</a>
* <a href = "https://www.youtube.com/embed/NzFMJwUR82k"> Logic Networks: (Example 2)</a>


Functions {data-navmenu="Section 3"}
=====================================

Column {.tabset}
-------------------------------------------------
### Functions

* <a href ="https://www.youtube.com/embed/-3hd821alPI">Functions (2005 Q4 Part A)  </a>
* <a href ="https://www.youtube.com/embed/cR5b2zWOa0w">Functions (2003 Q4 Part B) </a>
* <a href ="https://www.youtube.com/embed/IXs5CTQnBU4">Floor Functions Exercise HD	</a>
 
 
Mathematical Functions{data-navmenu="Section 3"}
=====================================

Column {.tabset}
-------------------------------------------------

### Logarithms

### Exponennts

### Tutorial


Invertible Functions {data-navmenu="Section 3"}
=====================================

Column {.tabset}
-------------------------------------------------

### Invertible Functions



Graph Theory {data-navmenu="Section 4"}
====================================

Column{.tabset}
----------------------------------------------

### Graph Theory

Graph theory is the study of points and lines. In particular, it involves the ways in which sets of points, called ***vertices***, can be connected by lines, called ***edges***.

Graphs are classified according to their complexity, the number of edges allowed between any two vertices, and whether or not directions are assigned to edges.

### Videos

* <a href="https://www.youtube.com/watch?v=6eg9V-LzCFQ">Basic definitions</a>  – 2010 Question [4:58]
* <a href="https://www.youtube.com/watch?v=MNoXLskj93k">Graph Theory – Walks and Paths</a> [9:20]
* <a class="vm-video-title-content yt-uix-sessionlink" href="https://www.youtube.com/watch?v=u5_r_GOd7NM">Traversable and Eulerian Graphs</a> [11:22]
* <a title="Weighted Graphs " href="http://youtu.be/MurOpIGCmhQ" target="_blank">Weighted Graphs</a> [6:02]
* <a title="Degree Sequence of a Graph" href="https://www.youtube.com/watch?v=D-W7VdUQBto" target="_blank">Degree Sequence of a Graph</a>
* <a title="Complete Graphs" href="http://youtu.be/wvoEtJOht9g" target="_blank">Complete Graphs</a>
* <a title="Regular Graphs" href="http://youtu.be/W757kOQvDww" target="_blank">Regular Graphs</a>
* <a title="Adjacency List" href="http://youtu.be/pms38inEdzg" target="_blank">Adjacency List:</a> Using an adjacency list to construct a graph.
* <a title="Adjacency List" href="http://youtu.be/imYq0rFJlHc" target="_blank">Adjacency List</a> ( Worked Example)
* <a title="Paths and Cycles in Graph Theory" href="http://youtu.be/baEtZGjpDLk" target="_blank">Paths and Cycles in Graph Theory</a>
* <a title="Non-Isomorphic Graphs" href="http://youtu.be/U-7kcP6AZX8" target="_blank">Non-Isomorphic Graphs</a> [4:01]
* <a href="https://www.youtube.com/watch?v=Xq8o-z1DsUA">Isomorphic Graphs – Example 1</a> [8:29]
* <a href="https://www.youtube.com/watch?v=KejZccQTDF8">Isomorphic Graphs – Example 2</a> [ 3:40]
* <a href="http://youtu.be/xcOrrJGxzu8" target="_blank">Isomorphic Graphs </a>[5:16]
* <a href="http://youtu.be/PIGyXIWeqZg" target="_blank">Walks and Paths in Graphs</a> [9.20]
* <a class="vm-video-title-content yt-uix-sessionlink" href="https://www.youtube.com/watch?v=E4GNXq9dUO0">Eulers Formula for Planar Graphs</a> [5:42]


### Graph Theory Terms


#### Graph Theory 

*  <a href="https://www.youtube.com/watch?v=tL7l5E1NnS8">Introduction to Graph Theory – Part 1</a> [9:27]
*  <a href="https://www.youtube.com/watch?v=xozFOG8xQJw">Introduction to Graph Theory – Part 2</a> [6:29]
*  <a href="https://www.youtube.com/watch?v=aqsDGlbja3s">Introduction to Graph Theory – Part 3</a> [11:24]
*  <a href="https://www.youtube.com/watch?v=6eg9V-LzCFQ">Basic definitions</a>  – 2010 Question [4:58]
*  <a href="https://www.youtube.com/watch?v=MNoXLskj93k">Graph Theory – Walks and Paths</a> [9:20]
*  <a href="https://www.youtube.com/watch?v=u5_r_GOd7NM">Traversable and Eulerian Graphs</a> [11:22]
*  <a title="Weighted Graphs " href="http://youtu.be/MurOpIGCmhQ" target="_blank">Weighted Graphs</a> [6:02]




* <a href="https://www.youtube.com/embed/s1f3nCOOzz8"></a>
* <a href="https://www.youtube.com/embed/imYq0rFJlHc">Adjacency List ( Worked Example)</a>
* <a href="https://www.youtube.com/embed/xcOrrJGxzu8">Isomorphic Graphs [5:16]</a>


* <a href="https://www.youtube.com/embed/D-W7VdUQBto">Degree Sequence of a Graph</a>
* <a href="https://www.youtube.com/embed/wvoEtJOht9g">Complete Graphs</a>
* <a href="https://www.youtube.com/embed/PIGyXIWeqZg">Walks and Paths in Graphs</a>



* <a href="https://www.youtube.com/embed/W757kOQvDww">Regular Graphs</a>
* <a href="https://www.youtube.com/embed/Xq8o-z1DsUA">Isomorphic Graphs – Example 1 </a>
* <a href="https://www.youtube.com/embed/U-7kcP6AZX8">Non-Isomorphic Graphs [4:01]</a>


* <a href="https://www.youtube.com/embed/E4GNXq9dUO0">Eulers Formula for Planar Graphs [5:42]</a>
* <a href="https://www.youtube.com/embed/baEtZGjpDLk">Paths and Cycles in Graph Theory </a>
* <a href="https://www.youtube.com/embed/pms38inEdzg">Adjacency List: Using an adjacency list to construct a graph.</a>


### Types of Graphs 

<h5>Directed Graphs</h5>
A directed graph is a graph where the arcs are one-directional, that is an arc between two nodes only indicates the possibility of moving from one node to the other, but not in the opposite direction. The arcs will usually be drawn as arrows to indicate the direction. An example of a potential use for a directed graph would be a graph which tracks possible states that a computer could be in; there may be a way for a computer in one state to reach a subsequent state, but no way to return from the second state to the first.

<h5>Weighted graph</h5>
A weighted graph is a graph where there is some 'cost' associated with each arc. Usually, a little number will appear directly adjacent to every arc to express this price. A typical use of a weighted graph would be planning routes between locations on a map where the 'cost' associated with the arc would be the distance between the two locations.

<h5>Trees</h5>
A tree is a special graph which is connected (every node can be reached from every other node by following one or more arcs) and for which the number of arcs is exactly one fewer than the number of nodes. A tree is usually drawn with one node (called the 'root node') at the top of the diagram, and then 'growing' downwards with arcs and nodes getting further and further from the root. In this way, nodes can be grouped in terms of their distance from the root. Every node (aside from the root) is referred to as the 'child' of the node to which it is connected and which is one step closer to the root. This node is also called the 'parent' node of the child. Every node has at most one parent but can have any number of children. Nodes without any children are commonly called 'leaf nodes'. A typical use of a tree would be a decision problem where the answer to a question determines the next question and set of possible answers.

<h5> Planar Graphs</h5>
A planar graph is a graph that can be drawn in the plane such that there are no edge crossings.

<h5>Characterization</h5>
The planar graphs can be characterized by a theorem first proven by Kazimierz Kuratowski in 1930, which states that the planar graphs are exactly those graphs G such that $K_5 \not \preceq G$  and $K_{3,3</h5> \not \preceq G$ .



<h5>Types of Graph Layouts</h5>

1. Bipartite Graphs
2. Path Graphs
3. Cycle Graphs
4. Null Graphs


<h5>Bipartite Graphs</h5>

* A bipartite graph is a graph whose vertex-set can be split into two sets in such a way that each edge of the graph joins a vertex in first set to a vertex in second set.



<h5>Path Graphs</h5>

* A path graph is a graph consisting of a single path. 
* The path graph with n vertices is denoted by $P_n$.



<h5>Cycle Graphs</h5>

* A cycle graph is a graph consisting of a single cycle. 
* The cycle graph with n vertices is denoted by $C_n$.



<h5>Null Graphs</h5>

* A null graphs is a graph containing no edges. * The null graph with n vertices is denoted by $N_n$.




There are various types of graphs depending upon the number of vertices, number of edges, interconnectivity, and their overall structure. We will discuss only a certain few important types of graphs in this chapter.


Trees {data-navmenu="Section 4"}
====================================

Column {.tabset}
----------------------------------------------

### Trees
* <a href ="//www.youtube.com/embed/TzLswrllE7E">    Spanning Trees - </a>
* <a href ="//www.youtube.com/embed/ueEOrbbB6Uw">     Trees 2006 Isomorphic Trees</a>
* <a href ="//www.youtube.com/embed/wVtE00YodYs">     Spanning Trees  - (Example 1)[10.55]</a>


* <a href ="//www.youtube.com/embed/1Nb1I8nfyx4">    Spanning Trees  - (Example 2)[7.06]</a>

* <a href ="//www.youtube.com/embed/tm8Ew3Vyj40">    Spanning Trees  - (Example 3)[9:35]</a>

* <a href ="//www.youtube.com/embed/p95zIv1eyME">    Binary Search Trees - Number of Records</a>

* <a href ="//www.youtube.com/embed/5J8ofTU13KU">    Non-Isomorphic Trees - [9:59]</a>
* <a href ="//www.youtube.com/embed/7EYf2XhxB4s">    Binary Search Trees  - Important Terminology</a>
* <a href ="//www.youtube.com/embed/GKWQbtPq6R0">    Binary Search Trees - Drawing a BST with 14 nodes.</a>

* <a href ="//www.youtube.com/embed/-MieB-QtX14">    Height of a Binary Search Tree</a>

* <a href ="//www.youtube.com/embed/Qkb_2I23DJo">    Binary Search Trees  - Example</a>
   

* <a href ="//www.youtube.com/embed/lU1RKxj6zXs">    Binary Search Trees - (Revision and 2004 Question) [ 8:39 ]</a>




### Binary Search Trees

A binary search tree (BST), sometimes also called an ordered or sorted binary tree, is a node-based binary tree data structure which has the following properties:

*  The left subtree of a node contains only nodes with keys less than the node's key.
*  The right subtree of a node contains only nodes with keys greater than the node's key.
*  The left and right subtree must each also be a binary search tree.
*  There must be no duplicate nodes.


### Spanning Trees

A spanning tree $T$ of a connected, undirected graph $G$ is a tree composed of all the vertices and some (or perhaps all) of the edges of $G$. 

Informally, a spanning tree of $G$ is a selection of edges of $G$ that form a tree spanning every vertex. That is, every vertex lies in the tree, but no cycles (or loops) are formed. On the other hand, every bridge of $G$ must belong to $T$.

A spanning tree of a connected graph $G$ can also be defined as a maximal set of edges of $G$ that contains no cycle, or as a minimal set of edges that connect all vertices.

#### Subgraphs

We say that a graph H is a subgraph of a graph G if its vertices are a subset of the
vertex set of G, its edges are a subset of the edge set of G, and each edge of H has
the same end-vertices in G and H.

#### Definition 
If H is a subgraph of G such that $V(H) = V (G)$, then H is called a spanning subgraph of G. If H is a spanning subgraph which is also a tree, then H is said to be a spanning tree of G.

### Traversals

A traversal is a process that visits all the nodes in the tree. Since a tree is a nonlinear data structure, there is no unique traversal. We will consider several traversal algorithms with we group in the following two kinds

* depth-first traversal
* breadth-first traversal


There are three different types of depth-first traversals, :

* Pre-Order traversal - visit the parent first and then left and right children;
* In-Order traversal - visit the left child, then the parent and the right child;
* Post-Order traversal - visit left child, then the right child and then the parent;



Relations and Digraphs {data-navmenu="Section 4"}
=====================================



Column {.tabset}
-------------------------------------------------

Digraphs and Relations

### Videos 

* < a href = ="https://www.youtube.com/embed/4vSr6q5Nxqc"> Digraphs and Relations</a>

*  < a href = ="https://www.youtube.com/embed/dHzu897SdDA">  Cartesian Products</a>

*  < a href = ="https://www.youtube.com/embed/4vSr6q5Nxqc">  Digraphs and Relations -Example</a>

* < a href = ="https://www.youtube.com/embed/eZIEc1O0W1w"> Relations Example 2</a>

*  < a href = ="https://www.youtube.com/embed/dHzu897SdDA">  Cartesian </a>

*  < a href = ="https://www.youtube.com/embed/4vSr6q5Nxqc">  Digraphs and Relations -Example</a>

* < a href = ="https://www.youtube.com/embed/rG8mhlqnkr0">  Relations -Example</a>

*  < a href = ="https://www.youtube.com/embed/_QTKlTJYKRA">  Transitive Relations</a>

*  < a href = ="https://www.youtube.com/embed/A08P9ZJsLOs">  Relations -Example</a>



### Room 2






<h5> Social Network Analysis of the 1916 rising (James Nagle)</h5>

### Room 3

<h5>Building smarter solutions with no expertise in machine learning (Laurent Picard)</h5>



Sequences and Series {data-navmenu="Section 5"}
=====================================

Column {.tabset}
-------------------------------------------------

### Introduction 

* Sequences - what are sequences?
* Arithmetic Progressions
* Geometric Progressions
* Recurrences Relationships (Fibonacci Sequence)

### Videos

*  Part 1 : Sequences
*  Part 2 : Proof by Induction
*  Part 3 : Series and the Sigma Notation


* <a href="https://www.youtube.com/embed/FsnDh03YYVQ"> Sequences and Series - Sequences</a>
* <a href="https://www.youtube.com/embed/puPz1kBzoi4"> Sequences and Series : Basic Sequences	</a>
* <a href="https://www.youtube.com/embed/puPz1kBzoi4">Sequences and Series : Basic Sequences	</a>
* <a href="https://www.youtube.com/embed/wGzpAfUTJTw"> Arithmetic Progressions (Sequences and Series)</a>
* <a href="https://www.youtube.com/embed/sAm0PHazpvQ"> Sequences and Series - Geometric Series</a>
* <a href="https://www.youtube.com/embed/OvHeYH9mNkA">Geometric Series (Sequence and Series)</a>
    
 
* <a href="https://www.youtube.com/embed/4yQaMo9zqCs"> Series Part 1</a>
* <a href="https://www.youtube.com/embed/hoodEvYAGxQ"> Sequences 2001 basic sequences</a>
* <a href="https://www.youtube.com/embed/oZgnNIUZSVA">Sequences and Series 2002 evaluating a series</a>
      
* <a href="https://www.youtube.com/embed/mUws2ruOP9k"> Sequences and Series 2001 summations</a>
* <a href="https://www.youtube.com/embed/BCzU5smvhMY"> Recurrence Relations 2004</a>

*  <a href="http://youtu.be/r5SiDTplMwI">Sigma Notation</a> [6.49]
*  <a title="Sequence Expression" href="http://youtu.be/vLAorai793I" target="_blank">Determining Sequence Expressions</a>
*  <a title="Finite Series" href="http://youtu.be/NnuAIuvf73U" target="_blank">Finite Series</a> :  Summation of a sequence.


* <a href="https://www.youtube.com/embed/D8zZ7nr80r8">    Sigma Notation</a>
* <a href="https://www.youtube.com/embed/lwjpA522bnY">    Finite Series</a>

    
* <a href="https://www.youtube.com/embed/NhUBAYcfY_A">Evaluating the Sum of a Series</a>
  
* <a href="https://www.youtube.com/embed/sAm0PHazpvQ">Geometric Series </a>

* <a href="https://www.youtube.com/embed/XVyyGuMtyPo">Geometric Summation Exercise</a>
 
  
  


#### Sigma Notation and Finite Series

*  <a href="https://www.youtube.com/watch?v=O8y3OInkTsg" target="_blank">Sigma Notation</a> (6:49 Minutes)
*  Finite Series – <a title="Sequences and Series : Finite Series " href="https://www.youtube.com/watch?v=HQ-nWl6Xfn4" target="_blank">HERE</a> (4:40 Minutes)
*  Evaluating the Sum of a Series – <a href="http://youtu.be/NhUBAYcfY_A" target="_blank">HERE</a> ( 3:12 Minutes)

#### Geometric Series

*  Geometric Series - <a href="https://www.youtube.com/watch?v=sAm0PHazpvQ" target="_blank">HERE</a>  - [14:41]
*  <a href="https://www.youtube.com/watch?v=XVyyGuMtyPo">Geometric Summation Exercise</a>



#### Series 

*  Evaluating the Sum of a Series – <a href="http://youtu.be/NhUBAYcfY_A" target="_blank">HERE</a> ( 3:12 Minutes)


		
#### Proof by Induction
  
*  <a href="https://www.youtube.com/watch?v=VbO3eX1YKiM">Proof By Induction Example </a>
	

    

#### Sequences

*  Sequences – <a href="http://youtu.be/dZpq0JV_5vI" target="_blank">HERE</a>
*  Sequences Value Determination – <a href="http://youtu.be/Q8AeZu2g6nk" target="_blank">HERE</a> (2:24 Minutes)
*  Arithmetic Progressions - <a href="https://www.youtube.com/watch?v=wGzpAfUTJTw" target="_blank">HERE </a> (7:00)



*  Sequences – <a href="http://youtu.be/dZpq0JV_5vI" target="_blank">HERE</a>
*  Sequences Value Determination – <a href="http://youtu.be/Q8AeZu2g6nk" target="_blank">HERE</a> (2:24 Minutes)
*  Arithmetic Progressions - <a href="https://www.youtube.com/watch?v=wGzpAfUTJTw" target="_blank">HERE </a> (7:00)


#### Proof by Induction

	<li class="sharedaddy sd-like-enabled sd-sharing-enabled">Simple Example - <a href="https://youtu.be/Jqd_Mvpxsbo" target="_blank">HERE</a> [ 6:14 ]


#### Series 

*  Sigma Notation - <a href="https://youtu.be/D8zZ7nr80r8" target="_blank">Here</a> [6:49]
*  Finite Series – <a title="Sequences and Series : Finite Series " href="http://youtu.be/lwjpA522bnY" target="_blank">HERE</a> (4:40 Minutes)
*  Evaluating the Sum of a Series – <a href="http://youtu.be/NhUBAYcfY_A" target="_blank">HERE</a> ( 3:12 Minutes)
*  Geometric Series - <a href="https://www.youtube.com/watch?v=sAm0PHazpvQ" target="_blank">HERE</a>  - [14:41]
*  <a href="https://www.youtube.com/watch?v=XVyyGuMtyPo">Geometric Summation Exercise</a>




#### Sequences and Series

*  Sequences - <a href="http://Sequences" target="_blank">HERE</a>
*  Introduction to Sequences and Series – <a href="https://youtu.be/z2m2fscysX0" target="_blank">HERE</a>
*  Sequences Value Determination – <a href="https://www.youtube.com/watch?v=4pdtlxc2UKs" target="_blank">HERE</a> (2:24 Minutes)
*  Arithmetic Progressions - <a href="https://www.youtube.com/watch?v=wGzpAfUTJTw" target="_blank">HERE </a> (7:00 Minutes)

### Telescoping Series

	
#### Videos

*  <a title="Evaluating Sequence Values" href="https://www.youtube.com/watch?v=GcVEi0gP820" target="_blank">Introduction to </a><a href="https://www.youtube.com/watch?v=wQ4_kSZAkAQ">Sequences – Part 1</a> [4:09]
*  <a href="https://www.youtube.com/watch?v=Mj0Z1ts8U0k">Introduction to Sequences – Part 3</a> [8:27]
*  <a title="Evaluating Sequence Values" href="https://www.youtube.com/watch?v=GcVEi0gP820" target="_blank">Evaluating Sequence Values</a>

*  Exam Question <a href="https://www.youtube.com/watch?v=TZ_k798VNdk">Sequences and Series 2003 proof by induction</a>


<strong>Telescoping Series</strong>

*  <a href="https://www.youtube.com/watch?v=CcYnFbo8-xw">Telescoping Series (Lecture)</a>
*  Telescoping Series - Worked Example - <a href="http://Telescoping%20Series (Lecture)" target="_blank">HERE</a>


Finite Series {data-navmenu="Section 5"}
=====================================

Column {.tabset}
-------------------------------------------------


### Finite Series and Sigma Notation
Mathematical notation uses a symbol that compactly represents summation of many similar terms: the summation symbol, $\sum$, an enlarged form of the upright capital Greek letter *Sigma*. 

This is defined as:
\[\sum_{i=m}^n a_i = a_m + a_{m+1} + a_{m+2} +\cdots+ a_{n-1} + a_n. \]
Where, i represents the index of summation; ai is an indexed variable representing each successive term in the series; m is the lower bound of summation, and n is the upper bound of summation. The "i = m" under the summation symbol means that the index i starts out equal to m. The index, i, is incremented by 1 for each successive term, stopping when i = n.
Here is an example showing the summation of exponential terms (all terms to the power of 2):
\[\sum_{i=3}^6 i^2 = 3^2+4^2+5^2+6^2 = 86.\]
Informal writing sometimes omits the definition of the index and bounds of summation when these are clear from context, as in:
\[\sum a_i^2 = \sum_{i=1}^n a_i^2.\]


#### Three Important Summation Identities
(index term = i , Number of terms = n }


*  Identity 1
\[ \sum^{i=n}_{i=1} 1 = n \]
*  Identity 2  
\[ \sum^{i=n}_{i=1} i = \frac{n(n+1)}{2} \]
*  Identity 3 
\[ \sum^{i=n}_{i=1} i^2 = \frac{(2n+1)(n+1)(n)}{6} \]


### Partitioning of Summations 


For some integers $m$ and $n$, with $m<n$.

\[ \sum^{i=n}_{i=1} u_{i} = \sum^{i=m}_{i=1} u_{i} + \sum^{i=n}_{i=m+1} u_{i}\]

Suppose $n=100$ and $m=50$

\[ \sum^{i=100}_{i=1} u_{i} = \sum^{i=50}_{i=1} u_{i} + \sum^{i=100}_{i=51} u_{i}\]

\textbf{Example}
Evaluate the following expression:
\[ \sum^{i=100}_{i=51} (i+1) \]


***Step 1*** Evaluate this expression using the identities (notice the lower bound)
\[ \sum^{i=100}_{i=1} (i+1) \]
***Step 2*** From the outcome of step 1, subtract the following
\[ \sum^{i=50}_{i=1} (i+1) \]




<h5>Step 1</h5> Evaluate the following expression using the identities. In this step $n=100$
\[ \sum^{i=100}_{i=1} (i+1)  = \sum^{i=100}_{i=1} i  +  \sum^{i=100}_{i=1} 1  \]

1. First term \[\sum^{i=100}_{i=1} i  = \frac{100\times(100+1)}{2}  = 5050\]
2. Second term \[ \sum^{i=100}_{i=1} i  =  100\]


\[ \sum^{i=100}_{i=1} (i+1)  = 5050 + 100 = 5150 \]




<h5>Step 2</h5>
Evaluate the following expression using the identities. In this step $n=50$
\[ \sum^{i=50}_{i=1} (i+1)  = \sum^{i=50}_{i=1} i  +  \sum^{i=50}_{i=1} 1  \]

1. First term \[\sum^{i=50}_{i=1} i  = \frac{50\times(50+1)}{2}  = 1275\]
2. Second term \[ \sum^{i=50}_{i=1} i  =  50\]


\[ \sum^{i=50}_{i=1} (i+1)  = 1275 + 50 = 1325 \]


\[ \sum^{i=100}_{i=51} (i+1) = \sum^{i=100}_{i=1} (i+1)  - \sum^{i=50}_{i=1}(i+1)   \]

\[ \sum^{i=100}_{i=51} (i+1)  = 5150 - 1325 =\boldsymbol{3825} \]

### Sequences and Series


### Telescoping Series

#### Telescoping Series

* Telescoping Series - Worked Example - <a href="http://Telescoping%20Series (Lecture)" target="_blank">HERE</a>[6:20]

* Telescoping Series - Worked Example - <a href="http://Telescoping%20Series (Lecture)" target="_blank">HERE</a>[6:20]



*  <a href="https://www.youtube.com/watch?v=CcYnFbo8-xw">Telescoping Series (Lecture)</a>
*  Telescoping Series - Worked Example - <a href="http://Telescoping%20Series (Lecture)" target="_blank">HERE</a>



*  <a href="https://www.youtube.com/watch?v=CcYnFbo8-xw">Telescoping Series (Lecture)</a>
*  Telescoping Series - Worked Example - <a href="http://Telescoping%20Series (Lecture)" target="_blank">HERE</a>


*  Telescoping Series - Worked Example - <a href="http://Telescoping%20Series (Lecture)" target="_blank">HERE</a>[6:20]




Proof By Induction {data-navmenu="Section 5"}
=====================================

Column
----------------------------------

### Proof by Induction

* <a href="https://www.youtube.com/watch?v=Jqd_Mvpxsbo">Proof By Induction </a>/
* <a href="https://www.youtube.com/watch?v=Jqd_Mvpxsbo">Proof By Induction </a>
* <a href="https://www.youtube.com/watch?v=1q21_hbmZG8">Proof By Induction </a>
	

		
#### Revision Notes
  
*  <a href="https://www.youtube.com/watch?v=VbO3eX1YKiM">Proof By Induction Example </a>
	
#### Series 

*  Evaluating the Sum of a Series – <a href="http://youtu.be/NhUBAYcfY_A" target="_blank">HERE</a> 
#### Convergence Testing 

*  <a class="vm-video-title-content yt-uix-sessionlink" href="https://www.youtube.com/watch?v=1owq4xezLng">Convergence Test</a>
*  Ratio Test Exercise – <a href="http://youtu.be/ojL-Vtek2Mo" target="_blank">HERE</a> [5:19]






Probability {data-navmenu="Section 6"}
=====================================

Column {.tabset}
-------------------------------------------------

### Basics of Probability


### Room 1

<h5> High-Level APIs for Machine Learning (Iain Keaney) </h5>

Convergence Testing {data-navmenu="Section 5"}
=========================================

### Convergence Tests


*  <a href="https://www.youtube.com/watch?v=1owq4xezLng">Convergence Test</a>
*  Ratio Test Exercise – <a href="http://youtu.be/ojL-Vtek2Mo" target="_blank">HERE</a> [5:19]

*  Convergence Test- <a href="https://youtu.be/LWYiiY1rOqg" target="_blank">HERE</a>(3:13)
*  Ratio Test Exercise – <a href="https://youtu.be/Ka8OawOt_-w" target="_blank">HERE</a>[5:19]


#### Ratio Test


*  Ratio Test (2015 Exam Question) - <a href="https://youtu.be/TApQUje2kWs" target="_blank">HERE</a>
*  Ratio Test for Convergence (2011 Q4) - <a href="https://youtu.be/u5grewDLe68" target="_blank">HERE</a>


#### Ratio Test

*  Ratio Test (2009 Exam Question) - <a href="https://youtu.be/0sjwarDSa-0" target="_blank">HERE</a>
*  Important Taylor Series Expansions <a href="https://youtu.be/ItK4oTbuuOo" target="_blank">HERE</a>
*  Maclaurin Series Worked Example  <a href="https://youtu.be/tc-Zelm9bWA" target="_blank">HERE</a>
*  <a href="https://www.youtube.com/watch?v=Ka8OawOt_-w">Simple Ratio Test Exercise	 </a>
  
*  <a href="https://www.youtube.com/watch?v=quK-JQ5EQOE">The Ratio Test</a>
	
#### Ratio Test

*  Convergence Test- <a href="https://youtu.be/LWYiiY1rOqg" target="_blank">HERE</a>(3:13)
*  Ratio Test Exercise – <a href="https://youtu.be/Ka8OawOt_-w" target="_blank">HERE</a>[5:19]
*  Ratio Test (2015 Exam Question) - <a href="https://youtu.be/TApQUje2kWs" target="_blank">HERE</a>
*  Ratio Test for Convergence (2011 Q4) - <a href="https://youtu.be/u5grewDLe68" target="_blank">HERE</a>
*  Ratio Test (2009 Exam Question) - <a href="https://youtu.be/0sjwarDSa-0" target="_blank">HERE</a>


#### Convergence Testing 

*  <a class="vm-video-title-content yt-uix-sessionlink" href="https://www.youtube.com/watch?v=1owq4xezLng">Convergence Test</a>
*  Ratio Test Exercise – <a href="http://youtu.be/ojL-Vtek2Mo" target="_blank">HERE</a> [5:19]





 
  
*  <a href="https://www.youtube.com/watch?v=ItK4oTbuuOo">Important Taylor Series Expansions  </a>
	 
*  <a href="https://www.youtube.com/watch?v=tc-Zelm9bWA">Maclaurin Series Worked Example</a>
	

#### Convergence Testing 

*  <a class="vm-video-title-content yt-uix-sessionlink" href="https://www.youtube.com/watch?v=1owq4xezLng">Convergence Test</a>
*  Ratio Test Exercise – <a href="http://youtu.be/ojL-Vtek2Mo" target="_blank">HERE</a> [5:19]



   



Matrices {data-navmenu="Section 6"}
=====================================

Column {.tabset}
-------------------------------------------------

### Introduction

### Adding and Substracting Matrices


### Matrix Multiplication

* Method for multiply a pair of $2\times2$ matrices.

\[ \left(
\begin{array}{cc}
a_1 & a_2 \\ 
b_1 & b_2
\end{array} \right)\left(
\begin{array}{cc}
c_1 & d_1 \\ 
c_2 & d_2
\end{array} \right) = \left(
\begin{array}{cc}
(a_1 \times c_1) + (a_2 \times c_2) & (a_1 \times d_1) + (a_2 \times d_2) \\ 
(b_1 \times c_1) + (b_2 \times c_2) & (b_1 \times d_1) + (b_2 \times d_2)
\end{array} \right) \]

#### Example

\[ \left(
\begin{array}{cc}
1 & 3 \\ 
0 & 2
\end{array} \right)\left(
\begin{array}{cc}
1 & 2 \\ 
4 & 1
\end{array} \right) = \left(
\begin{array}{cc}
(1 \times 1) + (3 \times 4) & (1 \times 2) + (3 \times 1) \\ 
(0 \times 4) + (2 \times 4) & (0 \times 2) + (2 \times 1)
\end{array} \right) = \left(
\begin{array}{cc}
14 & 5 \\ 
8 & 2
\end{array} \right) \]


### Determinants


### Tutorials

Matrices Tutorial 1

* Question 1 <a href= "https://youtu.be/XCYf81OTDVc"> Here</a>
* Question 2 <a href= "https://youtu.be/z1aIiH4bE4k"> Here</a>
* Question 3  - Part 1 <a href= "https://youtu.be/FtyNlZIsiXg"> Here</a>
* Question 3  - Part 2 <a href= "https://youtu.be/Xwg6VB_ooHk"> Here</a>
* Question 4
* Question 5
* Question 6
* Question 7 <a href= "https://youtu.be/Jj_7KiXJb64"> Here</a>
* Question 8 <a href= "https://youtu.be/tdVrjFFq1A8"> Here</a>

Systems of Linear Equations {data-navmenu="Section 6"}
==================================

Column {.tabset}
-----------------------------




Counting Problems {data-navmenu="Section 6"}
==================================

Column {.tabset}
-----------------------------

### Counting Problems

<h5> Counting Problems </h5>


In this section we look at counting problems, including combinations and permutations.


#### Videos


* Counting Problems -  <a href="https://www.youtube.com/watch?v=9QVx6yXzfEM" target="_blank">HERE</a>
* Binomial Coefficients - <a href="https://youtu.be/S74rTbwKIDY" target="_blank">HERE</a>
* Probability and Combinations (The Hypergeometric Distribution) - <a href="https://www.youtube.com/edit?o=U&amp;video_id=BdkSlLgd5dc" target="_blank">HERE</a>(12:49)


  
* <a href ="https://www.youtube.com/embed/O2Xg1BdqQBM"> Binomial Coefficients - Proof of Identities 1</a>
* <a href ="https://www.youtube.com/embed/XXoUYJbESCY"> Binomial Coefficients - Proof of Identities 2</a>
* <a href ="https://www.youtube.com/embed/O8P0te8s-ms"> Binomial Coefficients - Examples</a> /
* <a href ="https://www.youtube.com/embed/ytvlX_-VrF8"> Binomial Coefficients - Proof of Identities 3</a> 
* <a href ="https://www.youtube.com/embed/ong5YXLf_7Q"> Binomial Coefficients - Team Selection</a>
* <a href ="https://www.youtube.com/embed/oWlmy3W92u4"> Permutations and Combinations</a>

### Combinations

<h5> Combinations </h5>

### Permutations