---
title: "Discrete Mathematics - Section 2"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


Discrete Mathematics {data-navmenu="Introduction"}
=====================================

Column {.tabset}
--------------------

### Binary Numbers and Hexadecimal Numbers

<a href="index.html">Back to main page</a>

<h4> Binary Numbers</h4>

A binary number is a number expressed in the base-2 numeral system or binary numeral system, a method of mathematical expression which uses only two symbols: typically "0" (zero) and "1" (one).





<h3>Hexadecimal Numbers</h3>

```{r child="Section_02/Numbers-BinaryNumbers.Rmd"}
```


```{r child="Section_02/Numbers-BinaryMultiplication.Rmd"}
```


```{r child="Section_02/Numbers-GrayCode.Rmd"}
```



```{r child="Section_02/Numbers-Hexadecimal.Rmd"}
```


```{r child="Section_02/Numbers-Otherbases.Rmd"}
```

```{r child="Section_02/Numbers-ConversionTable.Rmd"}
```


```{r child="TutorialSheets/Numbers-Tutorial-1.Rmd"}
```

```{r child="TutorialSheets/BinaryNumbers-Tutorial-1.Rmd"}
```

```{r child="TutorialSheets/BinaryNumbers-Tutorial-2.Rmd"}
```

```{r child="TutorialSheets/HexadecimalNumbers-Tutorials-1.Rmd"}
```


