---
title: "Discrete Mathematics"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


Discrete Mathematics {data-navmenu="Introduction"}
=====================================

Column {.tabset}
--------------------

### Contents

|| Section | Conponents ||
|--------|:-----:|:---------------------|----------|
| | **Section 1**| Introduction to Numbers, Numbers Systems, Binary Numbers, Hexadecimal Numbers, Octal Numbers | |
| | **Section 2**| Set Theory, Logic, Logic Networks | |
| | **Section 3**| Functions, Mathematical Functions, Invertible Functions, O-Notation| |
| | **Section 4**| Graph Theory, Trees, Binary Search Trees| |
| | **Section 5**| Sequences and Series, Telescoping Series, Finite Series, Proof by Induction, Convergence and Ratio Tests||
| | **Section 6**| Probability, Counting Problems, Matrices, Systems of Linear Equations||

### Discrete mathematics


Discrete mathematics is the common name for the fields of mathematics most generally useful in theoretical computer science. This includes computability theory, computational complexity theory, and information theory. 

*  \textbf{Computability theory} examines the limitations of various theoretical models of the computer, including the most powerful known model - the Turing machine. 

*  \textbf{Complexity theory} is the study of tractability by computer; some problems, although theoretically soluble by computer, are so expensive in terms of time or space that solving them is likely to remain practically unfeasible, even with rapid advance of computer hardware. 

*  Finally, \textbf{information theory} is concerned with the amount of data that can be stored on a given medium, and hence concepts such as compression and entropy.




```{r child="sourcefiles/Graphs-IntroductionToGraphs.Rmd"}
```

```{r child="sourcefiles/Graphs-Trees.Rmd"}
```





```{r child="sourcefiles/Graphs-BinarySearchTrees.Rmd"}
```

```{r child="sourcefiles/RelationsDigraphs-Introduction.Rmd"}
```


```{r child="TutorialSheets/GraphTheory-Tutorial-1.Rmd"}
```



```{r child="TutorialSheets/Trees-Tutorial-1.Rmd"}
```


```{r child="TutorialSheets/Digraphs-Tutorial-1.Rmd"}
```






```{r child="sourcefiles/SequenceSeries-IntroductionToSequencesSeries.Rmd"}
```

```{r child="sourcefiles/SequenceSeries-Progressions.Rmd"}
```


```{r child="sourcefiles/SequenceSeries-FiniteSeries.Rmd"}
```




```{r child="sourcefiles/SequenceSeries-TelescopingSeries.Rmd"}
```

```{r child="sourcefiles/SequenceSeries-RecurrenceRelations.Rmd"}
```


```{r child="sourcefiles/SequenceSeries-ProofbyInduction.Rmd"}
```



```{r child="sourcefiles/SequenceSeries-RatioTests.Rmd"}
```


```{r child="sourcefiles/SequenceSeries-ConvergenceTests.Rmd"}
```


```{r child="TutorialSheets/Series-Tutorial-1.Rmd"}
```




Probability {data-navmenu="Section 6"}
=====================================

Column {.tabset}
-------------------------------------------------

### Basics of Probability


### Rules of Probability



```{r child="sourcefiles/CountingProblems.Rmd"}
```

   


```{r child="sourcefiles/Matrices-IntroductionToMatrices.Rmd"}
```


```{r child="TutorialSheets/Matrices-Tutorial-1.Rmd"}
```






