
Binary Numbers {data-navmenu="Section 1"}
=====================================

Column {.tabset}
----------------------------------

### Worksheet 1


#### Question 1

Express the following decimal numbers as binary numbers.


a. $(73)_{10}$

b. $(15)_{10}$

c. $(22)_{10}$

<hline> 

#### Question 2

All three answers are among the following options.


a.$(10110)_{2}$ %22

b.$(1111)_{2}$ %15

c. $(1001001)_{2}$ %73

d. $(1000010)_{2}$ %64

<hline> 

#### Question 3

Express the following binary numbers as decimal numbers


a.  $101$

b.  $1101$

c.  $11011$

d.  $100101$

<hline> 


#### Question 4 
Express the following binary numbers as decimal numbers.


a.$(101010)_{2}$

b.$(10101)_{2}$

c.$(111010)_{2}$

d. $(11010)_{2}$

<hline> 
#### Question 5

Express the following binary numbers as decimal numbers.


a.$(110.10101)_{2}$

b.$(101.0111)_{2}$

c. $(111.01)_{2}$

d. $(110.1101)_{2}$

<hline> 


<hline> 
#### Question 6

Express the following decimal numbers as binary numbers


a. 6
b. 15
c. 37
d. 77

<hline> 

\item Express the following decimal numbers as binary numbers.


a.$(27.4375)_{10}$%
b.$(5.625)_{10}$
c. $(13.125)_{10}$
d. $(11.1875)_{10}$

<hline> 

\item Perform the following binary additions.


a.$(110101)_{2}$ + $(1010111)_{2}$
b.$(1010101)_{2}$ + $(101010)_{2}$
c. $(11001010)_{2}$ + $(10110101)_{2}$
d. $(1011001)_{2}$ + $(111010)_{2}$

<hline> 




### Part B: Number Systems - Binary Arithmetic


Perform the following binary subtractions.
  

(a) $(110101)_{2}$ - $(1010111)_{2}$
(b) $(1010101)_{2}$ - $(101010)_{2}$
(c) $(11001010)_{2}$ - $(10110101)_{2}$
(d) $(1011001)_{2}$ - $(111010)_{2}$

  


#### Question 2 Perform the following binary multiplications.


(a) $(1001)_{2}\times( 1000)_{2}$  % 9 by 8
(b) $(101)_{2}\times(1101)_{2}$ % 5 by 11
(c) $(111)_{2}\times(1111)_{2}$ % 7 by 15
(d) $(10000)_{2}\times(11001)_{2}$%16 by 25





\section*{Part B: Number Systems - Binary Arithmetic}
%http://www.csgnetwork.com/binaddsubcalc.html
(See section 1.1.3 of the text)

  





### Worksheet 2

#### Question 1

Which of the following binary numbers is the result of this binary multiplication: $(10)_{2} \times ( 1101)_{2}$. % % (2) /  (13)


(a) $(11010)_{2}$ %26
(b) $(11100)_{2}$ %28
(c) $(10101)_{2}$ %21
(d) $(11011)_2$ %27



#### Question 3

Which of the following binary numbers is the result of this binary multiplication: $(1001110)_{2}\times ( 1101 )_{2}$. % (9) /  (3)


(a) $(11000)_{2}$ %24
(b) $(11001)_{2}$ %25
(c) $(10101)_{2}$ %21
(d) $(11011)_2$ %27



#### Question 5
 
Which of the following binary numbers is the result of this binary division: $(111001)_{2} \div ( 10011)_{2}$. % (57) /  (19)


(a) $(10)_2$ %2
(b) $(11)_{2}$ %3
(c) $(100)_{2}$ %4
(d) $(101)_{2}$ %5


#### Question 6

Which of the following binary numbers is the result of this binary division: $(101010)_{2} \div ( 111 )_{2}$. % (42) /  (7)


(a) $(11)_2$ %3
(b) $(100)_{2}$ %4
(c) $(101)_{2}$ %5
(d) $(110)_{2}$ %6


#### Question 7

Which of the following binary numbers is the result of this binary division: $(1001110)_{2} \div ( 1101 )_{2}$. % (78) /  (13)



(a) $(100)_{2}$ %4
(b) $(110)_{2}$ %6
(c) $(111)_{2}$ %7
(d) $(1001)_2$ %9







### Worksheet 3


#### Question 3

Which of the following binary numbers is the result of this binary division: $(1001110)_{2}\times ( 1101 )_{2}$. % (9) /(3)


a.$(11000)_{2}$ %24
b.$(11001)_{2}$ %25
c. $(10101)_{2}$ %21
d. $(11011)_2$ %27




<hline> 

#### Question 2 

Which of the following binary numbers is the result of this binary division: $(101010)_{2} \times( 111 )_{2}$. 

% (4) /(6)


a.$(11000)_{2}$ %24
b.$(11001)_{2}$ %25
c. $(10101)_{2}$ %21
d. $(11011)_2$ %27

<hline> 

#### Question 3

Which of the following binary numbers is the result of this binary division: $(1001110)_{2}\times ( 1101 )_{2}$. % (9) /(3)


a.$(11000)_{2}$ %24
b.$(11001)_{2}$ %25
c. $(10101)_{2}$ %21
d. $(11011)_2$ %27





<hline> 

\item Which of the following binary numbers is the result of this binary division: $(1001110)_{2}\times ( 1101 )_{2}$. % (9) /(3)


a.$(11000)_{2}$ %24
b.$(11001)_{2}$ %25
c. $(10101)_{2}$ %21
d. $(11011)_2$ %27

<hline> 

#### Question 7

Perform the following binary divisions.


a.$(1001000)_{2} \div ( 1000)_{2}$
b.$(101101)_{2} \div (1001)_{2}$
c. $(1001011000)_{2} \div (101000)_{2}$
d. $(1100000)_{2} \div (10000)_{2}$

<hline> 






### Worksheet 4

#### Question 1 : Binary numbers

Express the following binary numbers as decimal numbers


( i) $101$
( ii) $1101$
( iii) $11011$
( iv) $100101$



( b) Express the following decimal numbers as binary numbers


( i) 6
( ii) 15
( iii) 37
( iv) 77





#### Question 2

A number is expressed in base 5 as $(234)_5$. What is it as decimal number?
Suppose you multiply $(234)_5$ by 5. what would be the answer in base 5.


#### Question 3

Perform the following binary additions
 
  
a. $1011 + 1111$

b. $10101  + 10011$

c. $1010 + 11010$

d. $101010 + 10101 + 101$
  
 



#### Question 4

Perform the binary additions


* $(10111)_2 +(111010)_2$

* $(1101)_2 + (1011)_2 + (1111)_2$



#### Question 5}

Perform the binary subtractions using both the bit-borrowing method and the two's complement method.

* $(1001)_2 -(111)_2$

* $(110000)_2 -(10111)_2$




#### Question 6}

Perform the binary multiplications

* $(1101)_2 \times (101)_2$

* $(1101)_2 \times (1101)_2$




#### Question 7



( a) What is highest Hexadecimal number that can be written with two characters, and what is it's equivalent in decimal form?
What is the next highest hexadecimal number?

% \[FF = 255\] % Remark 
( b) Which of the following are not valid hexadecimal numbers?



( i) A5G 
( ii) 73 
( iii) EEF
( iv) 101







#### Question 8 : Binary Substraction}



( i) 110 - 10
( ii) 101 - 11  
( iii) 1001 - 11
( iv) 10001 - 100 
( v) 101001 - 1101
( vi) 11010101-1101






#### Question 9



( a) Suppose 2341 is a base-5 number
Compute the equivalent in each of the following forms:

( i) decimal number
( ii) hexadecimal number
( iii) binary number

( b) Perform the following binary additions

( i) $1011+ 1111$
( ii) $10101  + 10011$
( iii) $1010 + 11010$

### Worksheet 5


 



#### Question 1

Perform the following binary multiplications.


(a) $(1001000)_{2} \div ( 1000)_{2}$
(b) $(101101)_{2} \div (1001)_{2}$
(c) $(1001011000)_{2} \div (101000)_{2}$
(d) $(1100000)_{2} \div (10000)_{2}$


#### Question 2

Perform the following binary divisions.


(a) $(1001000)_{2} \div ( 1000)_{2}$
(b) $(101101)_{2} \div (1001)_{2}$
(c) $(1001011000)_{2} \div (101000)_{2}$
(d) $(1100000)_{2} \div (10000)_{2}$


#### Question 3

Which of the following binary numbers is the result of this binary division: $(111001)_{2} \div ( 10011)_{2}$.  (57) /  (19)


(a) $(10)_2$ 2
(b) $(11)_{2}$ 3
(c) $(100)_{2}$ 4
(d) $(101)_{2}$ 5


#### Question 4

Which of the following binary numbers is the result of this binary division: $(101010)_{2} \div ( 111 )_{2}$.  (42) /  (7)


(a) $(11)_2$ 3
(b) $(100)_{2}$ 4
(c) $(101)_{2}$ 5
(d) $(110)_{2}$ 6

#### Question 5

Which of the following binary numbers is the result of this binary division: $(1001110)_{2} \div ( 1101 )_{2}$.  (78) /  (13)



(a) $(100)_{2}$ 4
(b) $(110)_{2}$ 6
(c) $(111)_{2}$ 7
(d) $(1001)_2$ 9







#### Question 7

Perform the following binary multiplications.


a. $(1001000)_{2} \div ( 1000)_{2}$

b. $(101101)_{2} \div (1001)_{2}$

c. $(1001011000)_{2} \div (101000)_{2}$

d. $(1100000)_{2} \div (10000)_{2}$

#### Question 9

Perform the following binary division exercises.


a. $(1001000)_{2} \div ( 1000)_{2}$

b. $(101101)_{2} \div (1001)_{2}$

c. $(1001011000)_{2} \div (101000)_{2}$

d. $(1100000)_{2} \div (10000)_{2}$



#### Question 10

Calculate working in hexadecimal

\item $(BBB)_{16} + (A56)_{16}$
\item $(BBB)_{16} - (A56)_{16}$
 



#### Question 11}

Write the hex number $(EC4)_{16}$ in binary.
Write the binary number $(11110110101|)_2$ in hex.


#### Question 12}

Express the decimal number 753 in binary , base 5 and hexadecimal.



#### Question 13}

Express 42900 as a product of its prime factors, using index notation for repeated factors.



#### Question 14}

Expresse the recuring decimals 

( i) $0.727272\ldots$
( ii) $0.126126126....$
( iii) $0.7545454545...$
 
as rational numbers in its simplest form.



#### Question 15}
Given that $\pi$ is an irrational number, can you say whether $\frac{\pi}{2}$ is rational or irrational.
or is it impossible to tell?

- %
#### Question 16

a. Given x is the irrational positive number $\sqrt{2}$, express $x^8$ in binary notation

b. From part (i), is $x^8$ a rational number?




#### Question 17

a. 5/7 lies between 0.714 and 0.715.
b. $\sqrt(2)$ is at least 1.41.
c. $\sqrt(3)$  9s at least 1.732 and at most 1.7322.





#### Question 18

a. Write down the numbers 0.0000526 in floating point form.

b. How is the number 1 expressed in floating point form.





#### Question 19

a. Deduce that every composite integer $n$ has a prime factor such that $p \leq \sqrt{n}$.

b. Decide whether 899 is a prime.




#### Question 20

a. What would be the maximum numbber of digits that a decimal fraction with denominator 13 
could have in a recurring block in theory?

b. Can you predict which other fractions with denominator 13 will have the same digits as 1/13 in their recurring block?




### Worksheet 6


#### Question 1



Perform the following binary subtractions.


a. 110 - 10
b. 101 - 11
c. 1001 - 11
d. 10001 - 100 
e. 101001 - 1101
f. 11010101-1101

<hline> 

#### Question 4

Perform the binary subtractions using both the bit-borrowing method and the two's complement method.

a. $(1001)_2 -(111)_2$
b. $(110000)_2 -(10111)_2$





### Worksheet 7


#### Question 1

Express the following decimal numbers as binary numbers.
  

(i) $(73)_{10}$
(ii) $(15)_{10}$
(iii) $(22)_{10}$

  
All three answers are among the following options.
  

(a) $(10110)_{2}$ %22
(b) $(1111)_{2}$ %15
(c) $(1001001)_{2}$ %73
(d) $(1000010)_{2}$ %64

#### Question 2 

Express the following binary numbers as decimal numbers.
  

(a) $(101010)_{2}$
(b) $(10101)_{2}$
(c) $(111010)_{2}$
(d) $(11010)_{2}$

  
#### Question 3

Express the following binary numbers as decimal numbers.
  

(a) $(110.10101)_{2}$
(b) $(101.0111)_{2}$
(c) $(111.01)_{2}$
(d) $(110.1101)_{2}$
  

\item Express the following decimal numbers as binary numbers.
  

\item[i)] $(73)_{10}$
\item[ii)] $(15)_{10}$
\item[iii)] $(22)_{10}$

  

  All three answers are among the following options.
  

a.  $(10110)_{2}$ %22
b.  $(1111)_{2}$ %15
c.  $(1001001)_{2}$ %73
d.  $(1000010)_{2}$ %64

  

\item Express the following binary numbers as decimal numbers.
  

a.  $(101010)_{2}$
b.  $(10101)_{2}$
c.  $(111010)_{2}$
d.  $(11010)_{2}$

  
  \item Express the following binary numbers as decimal numbers.
  

a.  $(110.10101)_{2}$
b.  $(101.0111)_{2}$
c.  $(111.01)_{2}$
d.  $(110.1101)_{2}$

  
\item Express the following decimal numbers as binary numbers.
  

a.  $(27.4375)_{10}$  %
b.  $(5.625)_{10}$
c.  $(13.125)_{10}$
d.  $(11.1875)_{10}$

  

\item Perform the following binary multiplications.
%
%
%(a) $(1001000)_{2} \div ( 1000)_{2}$
%(b) $(101101)_{2} \div (1001)_{2}$
%(c) $(1001011000)_{2} \div (101000)_{2}$
%(d) $(1100000)_{2} \div (10000)_{2}$
%
%





%

\item Perform the following binary divisions.


%(a) $(1001000)_{2} \div ( 1000)_{2}$
%(b) $(101101)_{2} \div (1001)_{2}$
%(c) $(1001011000)_{2} \div (101000)_{2}$
%(d) $(1100000)_{2} \div (10000)_{2}$




%http://www.csgnetwork.com/binaddsubcalc.html
(See section 1.1.3 of the text)

\item Perform the following binary additions.
  

a.  $(110101)_{2}$ + $(1010111)_{2}$
b.  $(1010101)_{2}$ + $(101010)_{2}$
c.  $(11001010)_{2}$ + $(10110101)_{2}$
d.  $(1011001)_{2}$ + $(111010)_{2}$

  

\item Perform the following binary subtractions.
  

a.  $(110101)_{2}$ - $(1010111)_{2}$
b.  $(1010101)_{2}$ - $(101010)_{2}$
c.  $(11001010)_{2}$ - $(10110101)_{2}$
d.  $(1011001)_{2}$ - $(111010)_{2}$

  


\item Perform the following binary multiplications.


a.  $(1001)_{2}\times( 1000)_{2}$  % 9 by 8
b.  $(101)_{2}\times(1101)_{2}$ % 5 by 11
c.  $(111)_{2}\times(1111)_{2}$ % 7 by 15
d.  $(10000)_{2}\times(11001)_{2}$%16 by 25

 

\newpage

\item Perform the following binary multiplications.
%
%
%a.  $(1001000)_{2} \div ( 1000)_{2}$
%b.  $(101101)_{2} \div (1001)_{2}$
%c.  $(1001011000)_{2} \div (101000)_{2}$
%d.  $(1100000)_{2} \div (10000)_{2}$
%
%


\item Which of the following binary numbers is the result of this binary division: $(10)_{2} \times ( 1101)_{2}$. % % (2) /  (13)


a.  $(11010)_{2}$ %26
b.  $(11100)_{2}$ %28
c.  $(10101)_{2}$ %21
d.  $(11011)_2$ %27


\item Which of the following binary numbers is the result of this binary division: $(101010)_{2} \times( 111 )_{2}$. % (4) /  (6)


a.  $(11000)_{2}$ %24
b.  $(11001)_{2}$ %25
c.  $(10101)_{2}$ %21
d.  $(11011)_2$ %27


\item Which of the following binary numbers is the result of this binary division: $(1001110)_{2}\times ( 1101 )_{2}$. % (9) /  (3)


a.  $(11000)_{2}$ %24
b.  $(11001)_{2}$ %25
c.  $(10101)_{2}$ %21
d.  $(11011)_2$ %27




%----------------------------------------------------------------%

\item Perform the following binary divisions.
%
%
%a.  $(1001000)_{2} \div ( 1000)_{2}$
%b.  $(101101)_{2} \div (1001)_{2}$
%c.  $(1001011000)_{2} \div (101000)_{2}$
%d.  $(1100000)_{2} \div (10000)_{2}$
%
%


\item Which of the following binary numbers is the result of this binary division: $(111001)_{2} \div ( 10011)_{2}$. % (57) /  (19)


a.  $(10)_2$ %2
b.  $(11)_{2}$ %3
c.  $(100)_{2}$ %4
d.  $(101)_{2}$ %5


\item Which of the following binary numbers is the result of this binary division: $(101010)_{2} \div ( 111 )_{2}$. % (42) /  (7)


a.  $(11)_2$ %3
b.  $(100)_{2}$ %4
c.  $(101)_{2}$ %5
d.  $(110)_{2}$ %6


\item Which of the following binary numbers is the result of this binary division: $(1001110)_{2} \div ( 1101 )_{2}$. % (78) /  (13)



a.  $(100)_{2}$ %4
b.  $(110)_{2}$ %6
c.  $(111)_{2}$ %7
d.  $(1001)_2$ %9





  