Counting Problems - Worksheets {data-navmenu="Exercises"}
==================================

Column {.tabset}
-----------------------------



### Work Sheet 1


#### Question 1

\[ {n \choose k} = \frac{n!}{k! \times (n-k)!} \]
Evaluate the following:

* [1] ${5 \choose 2}$
* [2] ${5 \choose 0}$
* [3] ${6 \choose 3}$
* [4] ${6 \choose 6}$
* [5] ${10 \choose 1}$
* [6] ${10 \choose 9}$

#### Question 2


In how many ways can a group of four people be selected from three men and four women?
In how many of these groups are there more women than men?

#### Question 3

In how many ways can a group of five be selected from ten people
How many groups can be selected if two particular people from the ten can not be selected in the same group?\\

#### Question 4

The Venn Diagram shows the number of elements in each subset of set $S$.
If $P(A) = 3/10$ and $P(B) = 1/2$, find the values of $x$ and $y$

#### Question 5

* How many different four digit numners greater than 5000 can be formed from the digits ***2,4,5,8,9*** if each digit can only be used once in any given number. 
* How many of these numbers are odd?

#### Question 6

The code to open a combination lock is an ordered sequence of four digits
chosen from the set $\{1, 2, 3, 4, 5, 6, 7\}$. How many different codes are possible

a.  if repetition is allowed?
b.  if repetition is not allowed? 

#### Question 7 

Twelve balls numbered $\{1,2,3, \ldots ,12\}$ are placed in a container and three balls
are drawn at random without replacement. How many different selections of
three balls are possible, if the order of selection is not important?

#### Question 8

* In the experiment described in part (b), let $A$ be the event that the number on each ball drawn is at most 5. 
* Let $B$ be the event that the number on each ball drawn is odd. 
* Calculate the probability of each of the events $A$ , $B$, $A \cup B$ and $A \cap B$. 

