
Matrices - Worksheets {data-navmenu="Section 6"}
==================================

Column {.tabset}
-----------------------------



### Work Sheet 1

#### Question 1
Consider the following matrices $A} and $B} which are given as


\[ A = \left(
  \begin{array}{ccc}
0 & 2 & 1 \\
2 &1 &2\\
1 &2 &0\\
  \end{array}
\right) \qquad
B = \left(
\begin{array}{ccc}
1 &0 &1\\
2 &1 &0\\
1 &2 &1\\
\end{array}
\right)
\]

<h5> Questions </h5>

a. Show that $AB$ and $BA$ are not equal.

b. Find matrices $C$, $D$ and $E$ such that

  i.    $B$ + $C$ = $A$

  ii.    $BD$ = $B$

  iii.    $B$ - $E$ = $A$. 

<hline>

#### Question 2

\[A = \begin{bmatrix}
-4 & 3 \\
2 & 1 \\
\end{bmatrix} , \qquad
B = \begin{bmatrix}
4 & -2 \\
1 & 3 \\
\end{bmatrix}, \qquad
C = \begin{bmatrix}
-4 & 0 & 5 \\
1 & -3 & 2\\
\end{bmatrix}
\]

i. Calculate $2BC$

ii. Calculate $(A+B)C$

* <a href="https://youtu.be/z1aIiH4bE4k">Solution to this exercise</a>

<hline>

#### Question 3

\[A = \begin{bmatrix}
1 & 3 \\
-2 & 4 \\
\end{bmatrix} , \qquad
B = \begin{bmatrix}
2 & -3 & 7 \\
1 & 0 & 2 \\
\end{bmatrix}, \qquad
C = \begin{bmatrix}
1 & - 2 \\
4 & 3 \\
0 & 5 \\
\end{bmatrix}
\]



1. Calculate $A+BC$
2. Calculate $CB$

<h5> Solution</h5>

* <a href="https://youtu.be/FtyNlZIsiXg">Solution to this exercise (Part 1)</a>
* <a href="https://youtu.be/Xwg6VB_ooHk">Solution to this exercise (Part 2)</a>

#### Question 4


a. Write down the augmented matrix for the following system of equations.

b. Use Gaussian elimination to solve the system. 

<p>

#### Question 5


Calculate the following if possible: $AB$,$BA$, $AC$ and $C^{T}$
\[A = \begin{bmatrix}
2 & 2 \\
3 & 6 \\
\end{bmatrix} , \qquad
B = \begin{bmatrix}
-1 & 3 \\
2 & -2 \\
\end{bmatrix}, \qquad
C = \begin{bmatrix}
2 & - 2 \\
1 & 4 \\
1 & 1 \\
\end{bmatrix}
\]

<h5> Solution</h5>

* <a href="https://youtu.be/tdVrjFFq1A8">Solution to this exercise</a>

<p>

#### Question 6

Given the matrices

\[A = \begin{bmatrix}
0 & 2 & 3 \\
2 & 3 & 1
2 & 1 & 3 \\
\end{bmatrix} \mbox{ and }
B = \begin{bmatrix}
2  \\
4  \\
2  \\
\end{bmatrix}
\]

1. Calculate $AB$.

2. Find a matrix $X$ such that $AX = B$

3. Find a matrix $Y$ such that $AY = A$

<h5> Solution</h5>

* <a href="https://youtu.be/Jj_7KiXJb64">Solution to this exercise</a>

<p>


### Worksheet 2


#### Question 1

For the vectors given below, evaluate the following expressions where it is possible.
\[
\vec{u}=\left[ \begin{array}{c} 1 \\ 2 \\ 3 \end{array}\right],
\vec{v}=\left[ \begin{array}{c} -1 \\ 0 \\ 4 \end{array}\right],
\vec{x}=\left[ \begin{array}{c} 3 \\ 4 \end{array}\right],
\vec{y}=\left[ \begin{array}{c} -4 \\ 3 \end{array}\right],
\vec{w}=\left[ \begin{array}{c} 1 \\ 0\\ 2 \\ -5 \end{array}\right],
\vec{z}=\left[ \begin{array}{c} 2 \\ 2 \\ 2 \\ 3 \end{array}\right]
\]


*  $2\vec{u} + 3\vec{v}$
*  $3\vec{u} - \vec{v}$
*  $\vec{x} + 3\vec{v}$
*  $2\vec{z} - \vec{w}$
*  $\vec{u}+\vec{x}$
*  $\vec{v}+\vec{w}$
*  $\vec{u}\cdot \vec{v}$
*  $\left(2\vec{u}\right)\cdot \left(3\vec{v}\right)$
*  $\vec{x}\cdot \vec{y}$
*  $\vec{w} \cdot \vec{z}$
*  $\vec{w} \cdot (\vec{z}+\vec{w})$
*  $|\vec{x}|$
*  $|\vec{w}|$
*  $|\vec{y}|+|\vec{w}|$



#### Question 2

Calculate the angles between the pairs $\vec{u},\vec{v}$, $\vec{x},\vec{y}$, and $\vec{w},\vec{z}$ from the previous question. Give your answers in both radians and degrees.


#### Question 3

For the matrices below, evaluate the following expressions where it is possible.
\[
A=\left[ \begin{array}{cc} 1  & 2 \\ 3 & 4 \end{array}\right],
B=\left[ \begin{array}{cc} -2  & 0 \\ 1 & -7 \end{array}\right],
C=\left[ \begin{array}{ccc} 3  & 2 & -2 \\ 4 & 8 & 2 \end{array}\right],
D=\left[ \begin{array}{ccc} 3  & 2 & -2 \\ 4 & 8 & 2 \end{array}\right],
\]
\[
E=\left[ \begin{array}{ccc} 1  & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{array}\right],
F=\left[ \begin{array}{ccc} -1  & 0 & 2 \\ 3 & 4 & 1 \\  3 & 1 & 0 \end{array}\right],
\]
%-------------------%
\[
G=\left[ \begin{array}{cc}3 & 4 \\1 & 2 \\2 &-1 \\ \end{array}\right],
H=\left[ \begin{array}{ccc}3 & 4 & 3\\1 & 2 & 2\\ \end{array}\right],
I=\left[ \begin{array}{ccc}2 & 2 & 1\\ \end{array}\right],
\]

\[
J=\left[ \begin{array}{c}
3\\
1\\
1\\ \end{array}\right],
K=\left[ \begin{array}{ccc}
2 & 1 & 3\\1 & 2 & 2\\2 & 1 & 0\\\end{array}\right], 
\]



*  $2A+3B$
*  $3C-D$
*  $8A+4C$
*  $2000A+3000B$
*  $E-F$
*  $A\vec{x}$
*  $B\vec{x}$
*  $A\vec{y}+B\vec{x}$
*  $A\vec{u}$
*  $C\vec{x}$
*  $C\vec{w}$
*  $E\vec{u}$
*  $E\vec{w}-\vec{F}\vec{w}$





\[2x + y - z = 2\]
\[x - y + z = 4\]
\[x + 2y + 2z = 10\]
