Numbers - Worksheets {data-navmenu="Exercises"}
==================================

Column {.tabset}
-----------------------------



### Work Sheet 1

#### Question 1

<b> Part (a) </b>
How many Symbols are used in each System

i.  Decimal (Base 10)
ii. Binary (Base 2) 
iii. Hexadecimal (Base 16)


#### Question 2

State which of the following sets the following numbers belong to. 

[1)] $18$
[2)] $8.2347\ldots$
[3)] $\pi$
[4)] $1.33333\ldots$
[5)] $17/4$
[6)] $4.25$
[7)] $\sqrt{\pi}$
[8)] $\sqrt{25}$

The possible answers are

[a] Natural number : $\mb{N} \subseteq \mb{Z } \subseteq \mb{Q} \subseteq \mb{R}$
[b] Integer : $ \mb{Z } \subseteq \mb{Q} \subseteq \mb{R}$
[c] Rational Number : $ \mb{Q} \subseteq \mb{R}$
[d] Real Number $\mb{R}$


\end{enumerate}



\newpage





% \newpage
\section*{Part D: Natural, Rational and Real Numbers}
\begin{framed}

\item $\mb{N}$ : natural numbers (or positive integers) $\{1,2,3,\ldots\}$
\item $\mb{Z}$ : integers $\{-3,-2,-1,0,1,2,3,\ldots\}$

\item[$\ast$] (The letter $\mb{Z}$ comes from the word \emph{Zahlen} which means ``numbers" in German.)

\item $\mb{Q}$ : rational numbers
\item $\mb{R}$ : real numbers
\item $\mb{N} \subseteq \mb{Z } \subseteq \mb{Q} \subseteq \mb{R}$

\item[$\ast$] (All natural numbers are integers. All integers are rational numbers. All rational numbers are real numbers.)


### Binary Numbers

\item Express the following decimal numbers as binary numbers.
  

\item[i)] $(73)_{10}$
\item[ii)] $(15)_{10}$
\item[iii)] $(22)_{10}$

  

  All three answers are among the following options.
  

a.  $(10110)_{2}$ %22
b.  $(1111)_{2}$ %15
c. $(1001001)_{2}$ %73
d.  $(1000010)_{2}$ %64

  

\item Express the following binary numbers as decimal numbers.
  

a.  $(101010)_{2}$
b.  $(10101)_{2}$
c. $(111010)_{2}$
d.  $(11010)_{2}$

  
  \item Express the following binary numbers as decimal numbers.
  

a.  $(110.10101)_{2}$
b.  $(101.0111)_{2}$
c. $(111.01)_{2}$
d.  $(110.1101)_{2}$

  
\item Express the following decimal numbers as binary numbers.
  

a.  $(27.4375)_{10}$  %
b.  $(5.625)_{10}$
c.  $(13.125)_{10}$
d.  $(11.1875)_{10}$

  
### Binary Addition and Subtraction

#### Question 1

Perform the following binary additions.


a.  $(110101)_{2}$ + $(1010111)_{2}$
b.  $(1010101)_{2}$ + $(101010)_{2}$
c.  $(11001010)_{2}$ + $(10110101)_{2}$
d.  $(1011001)_{2}$ + $(111010)_{2}$

#### Question 2

Perform the following binary subtractions.

a.  $(110101)_{2}$ - $(1010111)_{2}$
b.  $(1010101)_{2}$ - $(101010)_{2}$
c.  $(11001010)_{2}$ - $(10110101)_{2}$
d.  $(1011001)_{2}$ - $(111010)_{2}$

  

### Binary Multiplication and Division

#### Question 1

Perform the following binary multiplications.


a.  $(1001)_{2}\times( 1000)_{2}$  % 9 by 8
b.  $(101)_{2}\times(1101)_{2}$ % 5 by 11
c.  $(111)_{2}\times(1111)_{2}$ % 7 by 15
d.  $(10000)_{2}\times(11001)_{2}$%16 by 25

 



\item Perform the following binary multiplications.
%\begin{multicols}{2}
%
%a.  $(1001000)_{2} \div ( 1000)_{2}$
%b.  $(101101)_{2} \div (1001)_{2}$
%c.  $(1001011000)_{2} \div (101000)_{2}$
%d.  $(1100000)_{2} \div (10000)_{2}$
%
%

Which of the following binary numbers is the result of this binary division: $(10)_{2} \times ( 1101)_{2}$. % % (2) /  (13)
\begin{multicols}{2}

a.  $(11010)_{2}$ %26
b.  $(11100)_{2}$ %28
c.  $(10101)_{2}$ %21
d.  $(11011)_2$ %27


\item Which of the following binary numbers is the result of this binary division: $(101010)_{2} \times( 111 )_{2}$. % (4) /  (6)
\begin{multicols}{2}

a.  $(11000)_{2}$ %24
b.  $(11001)_{2}$ %25
c.  $(10101)_{2}$ %21
d.  $(11011)_2$ %27


\item Which of the following binary numbers is the result of this binary division: $(1001110)_{2}\times ( 1101 )_{2}$. % (9) /  (3)
\begin{multicols}{2}

a.  $(11000)_{2}$ %24
b.  $(11001)_{2}$ %25
c.  $(10101)_{2}$ %21
d.  $(11011)_2$ %27


 Perform the following binary divisions.
%\begin{multicols}{2}
%
%a.  $(1001000)_{2} \div ( 1000)_{2}$
%b.  $(101101)_{2} \div (1001)_{2}$
%c.  $(1001011000)_{2} \div (101000)_{2}$
%d.  $(1100000)_{2} \div (10000)_{2}$
%
%

\begin{enumerate}
\item Which of the following binary numbers is the result of this binary division: $(111001)_{2} \div ( 10011)_{2}$. % (57) /  (19)
\begin{multicols}{2}

a.  $(10)_2$ %2
b.  $(11)_{2}$ %3
c.  $(100)_{2}$ %4
d.  $(101)_{2}$ %5


\item Which of the following binary numbers is the result of this binary division: $(101010)_{2} \div ( 111 )_{2}$. % (42) /  (7)
\begin{multicols}{2}

a.  $(11)_2$ %3
b.  $(100)_{2}$ %4
c.  $(101)_{2}$ %5
d.  $(110)_{2}$ %6


\item Which of the following binary numbers is the result of this binary division: $(1001110)_{2} \div ( 1101 )_{2}$. % (78) /  (13)
\begin{multicols}{2}


a.  $(100)_{2}$ %4
b.  $(110)_{2}$ %6
c.  $(111)_{2}$ %7
d.  $(1001)_2$ %9




### Number Bases - Hexadecimal

#### Question 1

Answer the following questions about the hexadecimal number systems

a.  How many characters are used in the hexadecimal system?
b.  What is highest hexadecimal number that can be written with two characters? 
c.  What is the equivalent number in decimal form?
d.  What is the next highest hexadecimal number?

#### Question 2

Which of the following are not valid hexadecimal numbers?
  

a.  $73$
b. $A5G$
c. $11011$
d. $EEF	$

  
#### Question 3

Express the following decimal numbers as a hexadecimal number.
  

a.  $(73)_{10}$
b. $(15)_{10}$
c. $(22)_{10}$
d. $(121)_{10}$

  
#### Question 4

Compute the following hexadecimal calculations.
  

a.  $5D2+A30$
b. $702+ABA$
c. $101+111$
d. $210+2A1$



