Connectivity {data-navmenu="Graphs"}
=====================================

Column {.tabset}
--------------------

### Graph Connectivity

<h4> Connectivity</h4>
Whether or not it is possible to traverse a graph from one vertex to another is dependent on how connected a graph is. 

#### Definition of Connectedness
* If there is a u-v path in G, then we say that u and v are connected
* If there is a u-v path for every pair of vertices u and v in G, then we say that $G$ is connected

#### Theorems on Connectedness
Theorem: Let G be a graph of order at least 3. If there are distinct vertices u and v in G so that G-u and G-v are both connected, then G is also connected. 
Proof: Let w be a G vertex, which is different from both u and v. We want to prove connectedness, i.e., that for every pair (x,y) of vertices in G, there is an x-y walk in G. We may consider three (partly overlapping) cases: 

* If neither x nor y is u, then there is an x-y walk in G-u, and this also is an x-y walk in G.
* If neither x nor y is v, then there is an x-y walk in G-v, and this also is an x-y walk in G.
* If ${x,y} = {u,v}$, then employ the first two cases in order to see that there is a u-w walk and a w-v walk. Combining them indeed yields a u-v walk.

#### Vertex and Edge Connectivity
A graph G is called k-connected if for every ${\displaystyle S\subseteq V(G)}$, and ${\displaystyle |S|<k} $, ${\displaystyle G-S}$ is connected, and ${\displaystyle |G|>k}$. 
 
Similarly, a graph G is called $ℓ {\displaystyle \ell } $ edge-connected if for every 
${\displaystyle S\subseteq E(G)}$
, and $ {\displaystyle |S|<\ell } $
, 
G − S {\displaystyle G-S} 
 is connected, and ${\displaystyle |G|>1} $
. 
The connectivity of G is the greatest k such that G is k-connected, and is denoted by ${\displaystyle \kappa (G)} $
. 
Relatedly, the edge-connectivity of G is the greatest 
ℓ {\displaystyle \ell } 
 such that G is 
ℓ {\displaystyle \ell } 
 edge-connected, and is denoted by ${\displaystyle \lambda (G)}$. 

#### Theorems on Connectivity[edit]
Theorem: Let G be a k-connected graph. Then, 
∀ i ∈ N , 0 ≤ i ≤ k {\displaystyle \forall i\in \mathbb {N} ,0\leq i\leq k} 
, G is i-connected. 
Proof: Since G is k-connected, for all ${\displaystyle S\subseteq V(G),|S|<k}$, 
${\displaystyle G-S}$ is connected. Then, since 
${\displaystyle i\leq k}$ , for all 
${\displaystyle S\subseteq V(G),|S|<i\leq k} $
, 
G − S {\displaystyle G-S} 
 is also connected. 

Theorem: Let G be a nontrivial graph. Then, ${\displaystyle \lambda (G)\leq \delta (G)}$.

#### Proof: 
* Take v a vertex of degree ${\displaystyle \delta (G)}$ in $G$. 
* Then, removing all edges in G that are incident with v disconnects v from the rest of the graph, provided that 
${\displaystyle |G|>\delta (G)+1}$. 
* Therefore, G cannot be ${\displaystyle \delta (G)}$ edge-connected, and so ${\displaystyle \lambda (G)\leq \delta (G)}$. 

#### Exercise: Connectivity
If G is $ {\displaystyle \ell } $
 edge-connected, show that G is also i edge-connected ${\displaystyle \forall i\in \mathbb {N} ,0\leq i\leq \ell }$
.
