Logarithms {data-navmenu="Functions"}
=====================================
  
Column {.tabset}
-------------------------------------------------
  
### Logarithms
<h4>Logarithms</h4>
In mathematics, the logarithm is the inverse function to exponentiation. That means the logarithm of a given number x is the exponent to which another fixed number, the base b, must be raised, to produce that number x. 
<p>
In the simplest case, the logarithm counts the number of occurrences of the same factor in repeated multiplication; e.g. since 1000 = 10 × 10 × 10 = 103, the "logarithm base 10" of 1000 is 3, or log10(1000) = 3. 
<p>
The logarithm of x to base b is denoted as logb (x), or without parentheses, logb x, or even without the explicit base, log x, when no confusion is possible, or when the base does not matter such as in big O notation.
<p>
The logarithm base 10 (that is b = 10) is called the decimal or common logarithm and is commonly used in science and engineering. The natural logarithm has the number e (that is b ≈ 2.718) as its base; its use is widespread in mathematics and physics, because of its simpler integral and derivative. The binary logarithm uses base 2 (that is b = 2) and is frequently used in computer science.

### Laws of Logarithms


#### Laws of Logarithms



Here we
assume x and y are positive real numbers.
1. $loga(xy) = loga(x) + loga(y)$
2. $loga(x/y)= loga(x) - loga(y)$
3. $loga (x^r) = r loga(x)$ for any real number r.




Here we
assume x and y are positive real numbers.


1. $\log_a(xy) = loga(x) + \log_a(y)$

2. $loga(x/y)= loga(x) - loga(y)$

3. $\log_a (x^r) = r \log_a(x)$ for any real number r.


