Recurrence Relation {data-navmenu="Progressions"}
==================================

Column {.tabset}
-----------------------------


### Recurrence Relation

#### Recurrence Relations 

* In mathematics, a recurrence relation is an equation that recursively defines a sequence, once one or more initial terms are given: each further term of the sequence is defined as a function of the preceding terms.
<p>
* The term difference equation sometimes (and for the purposes of this article) refers to a specific type of recurrence relation. However, "difference equation" is frequently used to refer to any recurrence relation.




Let the sequence $u_n$ be defined by the recurrence relation:
\[ u_{n+1} = u_n + 2n, \]

for $n=1,2,3,\ldots$. \\  Initial Condition: $u_1=1$.

Calculate $u_2$, $u_3$, $u_4$ and $u_5$, showing all your workings.

Starting with $n=1$,
\[ u_{n+1} = u_n + 2n, \]
\[ u_{(1)+1} = u_{1} + 2\times 1, \]
\[ u_{2} = 1 + 2, \]
\[ u_{2} = 3. \]

With $n=2$,
\[ u_{n+1} = u_n + 2n, \]
\[ u_{(2)+1} = u_{2} + 2\times 2, \]
\[ u_{3} = 3 + 4, \]
\[ u_{3} = 7. \]

With $n=3$,
\[ u_{n+1} = u_n + 2n, \]
\[ u_{(3)+1} = u_{3} + 2\times 3, \]
\[ u_{4} = 7 + 6, \]
\[ u_{4} = 13. \]

With $n=4$,
\[ u_{n+1} = u_n + 2n, \]
\[ u_{(4)+1} = u_{4} + 2\times 4, \]
\[ u_{5} = 13 + 8, \]
\[ u_{5} = 21. \]

The first five elements of the sequence are as follows:
\[ \{1,3,7,13,21, \ldots\}
\]


### Recurrence Relation

<h4>Recurrence Relation</h4>

* A recurrence relation is an equation that recursively defines a sequence, once one or more initial terms are given: 
each further term of the sequence is defined as a function of the preceding terms.
* The term difference equation sometimes refers to a specific type of recurrence relation. 

* However, "difference equation" is frequently used to refer to any recurrence relation.

------------------------

#### Worked Example 

Recurrence Relations

***CIS102 2004 Question 7 2 Marks***



*  Consider the sequence given by \[ 1, 4, 7, 10, 13, \ldots\]
*  State a recurrence relation which expresses the nth term, $u_n$, in terms of the$(n - 1)$th term, $u_{n-1}$, 
*  State a recurrence relation which expresses the nth term, $u_n$, in terms of the first term $u_1$.



*  $u_1$ = 1 , $u_2$ = 4, $u_3$ = 7 etc 
*  Difference in successive terms is 3.
*  Therefore we can say 
\[ u_n = u_{n-1} + 3 \]



*  Difference between $u_2$ and $u_1$ is 3 (i.e. $1 \times 3$).
*  Difference between $u_3$ and $u_1$ is 6 (i.e. $2 \times 3$)
*  Difference between $u_4$ and $u_1$ is 9 (i.e. $3 \times 3$)

*  In general the difference between $u_n$ and $u_1$ is $(n-1)\times 3$.
\[ u_{n} = u_1 + 3 \times (n-1) \]
\[ u_{n} = 1 + (3n-3) = 3n-2\]
*  Equivalently
\[ u_{n+1} = u_1 + 3n = 3n+1\]



*  Another sequence is defined by the recurrence relation 
\[ u_n = u_{n-1} + 2n-1 \] and
$u_1$ = 1.
*  Calculate $u_2$ , $u_3$ , $u_4$  and $u_5$ .
*  (Answers 1,4,9,16,25)


\[\begin{array}{|c|c|c|c|}
n    & u_{n-1} & 2n-1 & u_n \\ \hline
2      & 1         &  3   & u_2 = 4 \\ \hline
3      & 4         &  5   & u_3 = 9 \\ \hline
4      & 9         &  7   & u_4 = 16 \\ \hline
5      & 16        &  9   & u_5 = 25 \\ \hline
\end{array}\]

-------------------------



#### *{Recursive Sequences}

Many sequences are defined by a recursive rule. Here each term in the sequence is defined by previous terms. In order to begin the recursion, initial terms or \emph{base cases} must be specified. For example
\begin{align*}
  &\begin{cases}
a_0=&1\\
a_n=&n a_{n-1}
  \end{cases}
\end{align*}
\begin{align*}
  a_0=&1   & &\\
  a_1=&1 \cdot a_0 = 1 &=&1  \\
  a_2=&2 \cdot a_1 = 2 \cdot 1 &=&2  \\
  a_3=&3 \cdot a_2 = 3 \cdot 2 \cdot 1 &=&6  \\
  a_4=&4 \cdot a_3 = 4 \cdot 3 \cdot 2 \cdot 1 &=&24  \\
  a_5=&5 \cdot a_4 = 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1 &=&120  \\
  a_6=&6 \cdot a_5 = 6 \cdot 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1 &=&620
\end{align*}

This sequences defines the \emph{factorial function}. $n!$ is the product of the first $n$ integers.
\[ a_n = n! = n \cdot (n-1) \cdot \left( n-2 \right) \cdot \left( n-3 \right) \cdots 3 \cdot 2 \cdot 1 \]
This sequence grows very rapidly, with $10!=3628800$, and $100! \cong 9.33 \times 10 ^{157}$ is a number greater than the number of atoms in the known universe. The factorial sequence is one of the fastest growing elementary sequences. Note that by convention $0!=1$.

\subsubsection*{Fibonacci sequence/numbers}
The Fibonacci sequence is defined by the following recursive rule.
\begin{align*}
  &\begin{cases}
f_0=&0; \quad f_1=1\\
f_n=&f_{n-1}+f_{n-2}
  \end{cases}
\end{align*}
The current term $f_n$ in the sequence is the sum of the previous two terms. The first few elements of this sequence are listed in the table below.
\begin{center}
\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|c|}
\hline
$f_0$ & $f_1$ & $f_2$ & $f_3$ & $f_4$ & $f_5$ & $f_6$ & $f_7$ & $f_8$ & $f_9$ & $f_{10}$ & $f_{11}$  \\
\hline
0 & 1 & 1 & 2& 3 & 5 & 8 & 13 & 21 & 34 & 55 & 89 \\
\hline
\end{tabular}
\end{center}
This sequence is named after the Italian mathematician Fibonacci, who introduced the base-ten Hindu-Arabic numeral system into Europe. Fibonacci consider the sequence to arise from a pairs of rabbits, which each produce a new pair of rabbits every month. After two months, each new pair becomes a breeding pair and increases the sequence. He showed that the number of rabbit pairs obeys the recursive rule $f_n=f_{n-1}+f_{n-2}$, though there are other problems in which this sequence emerges -- for example, when computing the golden ratio.

One difficulty with recursive sequences is that in order to find later values in the sequence, all previous terms in the sequence must be computed first. This makes it difficult to compute a term like $f_{1000}$. In the case of the Fibonacci sequence, alternative formulas exist, but this will not be the case for many recursive sequences.

Both Heron's method and the Fast Reciprocal algorithm can be represented as recursive sequences. The base case of the algorithms is the initial guess $G$.

 {\bf Heron's method to find $\sqrt{S}$:}
\begin{align*}
  &\begin{cases}
h_0=&G\\
h_{n+1}=&\frac{1}{2} \left( h_n + \frac{S}{h_n} \right)
  \end{cases}
\end{align*}

 {\bf Fast Reciprocal algorithm to find $\dfrac{1}{D}$:}
\begin{align*}
  &\begin{cases}
r_0=&G\\
r_{n+1}=&r_n \left( 2-D r_n \right)
  \end{cases}
\end{align*}
The recursive rule can be written in terms of $a_{n}$ or $a_{n+1}$.




