Telescoping Series {data-navmenu="Sequences and Series"}
=====================================

Column {.tabset}
-------------------------------------------------

### Telescoping Series

<strong>Telescoping Series</strong>


* A telescoping series is a series whose partial sums eventually only have a finite number of terms after cancellation. 
* The cancellation technique, with part of each term cancelling with part of the next term, is known as the method of differences. 

*  <a href="https://www.youtube.com/watch?v=CcYnFbo8-xw">Telescoping Series (Lecture)</a>
*  Telescoping Series - Worked Example - <a href="http://Telescoping%20Series (Lecture)" >HERE</a>

* In mathematics, a telescoping series is a series whose partial sums eventually only have a fixed number of terms after cancellation.
* Such a technique is also known as the method of differences.



<p>






* A telescoping series does not have a set form, like the geometric and p-series do. 
* A telescoping series is any series where nearly every term cancels with a preceeding or following term. 
* For instance, the following series is telescoping. 




\[   \sum^{\infty}_{n=1} \frac{1}{n} - \frac{1}{n+1} \]



### Telescoping Series

In mathematics, a telescoping series is a series whose partial sums eventually only have a fixed number of terms after cancellation.[1][2] Such a technique is also known as the method of differences.
For example, the series
\[\sum_{n=1}^\infty\frac{1}{n(n+1)}\]
simplifies as
\[\begin{align}
\sum_{n=1}^\infty \frac{1}{n(n+1)} & {} = \sum_{n=1}^\infty \left( \frac{1}{n} - \frac{1}{n+1} \right) \\
{} & {} = \lim_{N\to\infty} \sum_{n=1}^N \left( \frac{1}{n} - \frac{1}{n+1} \right) \\
{} & {} = \lim_{N\to\infty} \left\lbrack {\left(1 - \frac{1}{2}\right) + \left(\frac{1}{2} - \frac{1}{3}\right) + \cdots + \left(\frac{1}{N} - \frac{1}{N+1}\right) } \right\rbrack  \\
{} & {} = \lim_{N\to\infty} \left\lbrack {  1 + \left( - \frac{1}{2} + \frac{1}{2}\right) + \left( - \frac{1}{3} + \frac{1}{3}\right) + \cdots + \left( - \frac{1}{N} + \frac{1}{N}\right) - \frac{1}{N+1} } \right\rbrack = 1.
\end{align}\]


<p>



For example, the series
\[\sum_{n=1}^\infty\frac{1}{n(n+1)}\]
simplifies as
\begin{align}
\sum_{n=1}^\infty \frac{1}{n(n+1)} & {} = \sum_{n=1}^\infty \left( \frac{1}{n} - \frac{1}{n+1} \right) \\
{} & {} = \lim_{N\to\infty} \sum_{n=1}^N \left( \frac{1}{n} - \frac{1}{n+1} \right) \\
{} & {} = \lim_{N\to\infty} \left\lbrack {\left(1 - \frac{1}{2}\right) + \left(\frac{1}{2} - \frac{1}{3}\right) + \cdots + \left(\frac{1}{N} - \frac{1}{N+1}\right) } \right\rbrack  \\
{} & {} = \lim_{N\to\infty} \left\lbrack {  1 + \left( - \frac{1}{2} + \frac{1}{2}\right) + \left( - \frac{1}{3} + \frac{1}{3}\right) + \cdots + \left( - \frac{1}{N} + \frac{1}{N}\right) - \frac{1}{N+1} } \right\rbrack = 1.
\end{align}

Look at the partial sums:


\[   \sum^{n}_{i=1}  \frac{1}{i}  - 1/(i+1) = (1/1 - 1/2) + (1/2 - 1/3) + \ldots + (1/n - 1/(n+1))\]

\[= 1 - 1/(n+1)\]

because of cancellation of adjacent terms. 

So, the sum of the series, which is the limit of the partial sums, is 1.

<p>

#### Convergence

You do have to be careful; not every telescoping series converges. Look at the following series:

\[   \sum^{\infty}_{i=1} n - (n + 1) \]

You might at first think that all of the terms will cancel, and you will be left with just 1 as the sum.. But take a look at the partial sums:

\[   \sum^{n}_{i=1} - (i + 1) = (1 - 2) + (2 - 3) + \ldots + (n - (n + 1)) =\]

\[1 - (n + 1) =\]
\[-n.\]


<p>



This sequence does not converge, so the sum does not converge. This can be more easily seen if you simplify the expression for the term. You find that

\[   \sum^{\infty}_{i=1} n - (n + 1) = \sum^{\infty}_{i=1} -1 \]

and any infinite sum with a constant term diverges.



	
### Videos

*  <a title="Evaluating Sequence Values" href="https://www.youtube.com/watch?v=GcVEi0gP820" >Introduction to </a><a href="https://www.youtube.com/watch?v=wQ4_kSZAkAQ">Sequences – Part 1</a> [4:09]
*  <a href="https://www.youtube.com/watch?v=Mj0Z1ts8U0k">Introduction to Sequences – Part 3</a> [8:27]
*  <a title="Evaluating Sequence Values" href="https://www.youtube.com/watch?v=GcVEi0gP820" >Evaluating Sequence Values</a>

*  Exam Question <a href="https://www.youtube.com/watch?v=TZ_k798VNdk">Sequences and Series 2003 proof by induction</a>


