Specifying Sets {data-navmenu="Set Theory"}
=====================================

Column {.tabset}
--------------------

### Specifying Sets


#### Specifying Sets


<h3>NOTATIONS FOR A SET:</h3>

A set can be represented by two methods:
1.ROSTER METHOD
2.BUILDER METHOD

#### ROSTER METHOD:

In this method the elements of a set are separated by commas and are enclosed within curly brackets { }. For example:

* A = {1, 2, 3, 4, 5, 6} is a set of numbers.

* $B = \{Albert, Brianna, Carmel, David, Edward\}$ is a set of names.

* $C = \{a, e, i, o, u\}$ is a set of vowels.

* $D = \{apple, banana, guava, orange, pear\}$ is a set of fruits.

Listing the elements in this way is called Roster method. In this method, it is not necessary for the elements to be listed in a particular order. The elements of the set can be written just plainly, separated by commas and in any order.

<p> 
#### BUILDER METHOD:

This method is also called Property method. In Builder method, a set is represented by stating all the properties which are satisfied by the elements of that particular set only.

For example:

If A is a set of elements less than 0, then in Builder method it will be written as

A = {x: x < 0}, this statement is read as "**the set of all x such that x is less than 0**"

If A is a set of all real numbers less than 7, then in Builder method it is written as $A = {x   R: x < 7}$

Similarly,

* A = {2i: i is an integer} is a set of all even integers.

* $A = {x   R: x ? 2}$ is a set of all real numbers except 2.

* $A = \{x   R: x > 3 and x < 7\}$ is a set of real numbers greater than 3 but less than 7.

* A = {x   Z: x > 6} is a set of integers greater than 6.

* $A = {x   Z: 2x + 1}$ is a set of all odd integers.
