Types of Set {data-navmenu="Set Theory"}
====================================

Column {.tabset}
-------------------------------------------------------------



### Types of Sets
Sets can be classified into many types. Some of which are finite, infinite, subset, universal, proper, singleton set, etc.


#### The Universal Set and the Empty Set

*  The first is the {\textit{universal set}}, typically denoted $U$. This set is all of the elements that we may choose from. 

This set may be different from one setting to the next. 

*  For example one universal set may be the set of all real numbers, denoted $\mathbb{R}$, whereas for another problem the universal set may be the whole numbers $\{0, 1, 2,\ldots\}$.

*  The other set that requires consideration is called the \textit{{empty set}}. 

The empty set is the unique set is the set with no elements. We write this as $\{ \}$ and denote this set by $\emptyset$.



#### Finite Set
A set which contains a definite number of elements is called a finite set.

\subsubsection*{Example} \[S=\{x|x \in N and 70 >x>50\}\]

#### Infinite Set

A set which contains infinite number of elements is called an infinite set.

\subsubsection*{Example} 

\[S={x|x\in N  and x>10}\]

#### Subset
A set X is a subset of set Y (Written as $X \subseteq Y$) if every element of X is an element of set Y.

Example 1 − Let, $X={1,2,3,4,5,6}$ and Y={1,2}Y={1,2}. Here set Y is a subset of set X as all the elements of set Y is in set X. 

Hence, we can write $Y\subseteq X$.

Example 2 − Let, $X={1,2,3}$ and $Y={1,2,3}$. Here set Y is a subset (Not a proper subset) of set X as all the elements of set Y is in set X. Hence, we can write $Y\subseteqX$.



#### Example

 Let, $X={1,2,3,4,5,6}$ and $Y={1,2}$. Here set $Y \subset X$ since all elements in $Y$ are contained in $X$ too and $X$ has at least one element is more than set YY.

#### Universal Set


It is a collection of all elements in a particular context or application. All the sets in that context or application are essentially subsets of this universal set. Universal sets are represented as $U$.

#### Example

We may define $U$ as the set of all animals on earth. In this case, set of all mammals is a subset of $U$, set of all fishes is a subset of $U$, set of all insects is a subset of $U$, and so on.

#### Empty Set or Null Set
An empty set contains no elements. It is denoted by $\varnothing$. As the number of elements in an empty set is finite, empty set is a finite set. The cardinality of empty set or null set is zero.

#### Example

\[S={x|x\in N \mbox{ and }7<x<8}=\varnothing\]



Another set which has a special letter to denote it is the set containing no elements. This is called
the empty or null set and denoted by the symbol (D. 
Example 2.6 The set of integers m such that m2 = 5 is the empty set. 




#### Singleton Set or Unit Set

Singleton set or unit set contains only one element. A singleton set is denoted by {s}{s}.

#### Example

$S={x|x\in N, 7<x<9} = {8}$

#### Equal Set
If two sets contain the same elements they are said to be equal.

<h3>Example</h3>

If A={1,2,6}A={1,2,6} and B={6,1,2}B={6,1,2}, they are equal as every element of set A is an element of set B and every element of set B is an element of set A.

#### Equivalent Set
If the cardinalities of two sets are same, they are called equivalent sets.

#### Example

If A={1,2,6}A={1,2,6} and B={16,17,22}B={16,17,22}, they are equivalent as cardinality of A is equal to the cardinality of B. i.e. |A|=|B|=3|A|=|B|=3

#### Overlapping Set

Two sets that have at least one common element are called overlapping sets.

In case of overlapping sets −

\[n(A\cupB)=n(A)+n(B)−n(A\cap B)\]
\[n(A\cupB)=n(A−B)+n(B−A)+n(A\cap B)\]
\[n(A)=n(A−B)+n(A\cap B)\]
\[n(B)=n(B−A)+n(A\cap B)\]

#### Example

Let, $A={1,2,6}$ and $B={6,12,42}$. There is a common element ‘6’, hence these sets are overlapping sets.


### Disjoint Set

Two sets A and B are called disjoint sets if they do not have even one element in common. 
Therefore, disjoint sets have the following properties −

\[n(A\cap B)=\varnothing\]
\[n(A\cup B)=n(A)+n(B)\]
#### Example 

Let, A={1,2,6}A={1,2,6} and B={7,9,14}B={7,9,14}, there is not a single common element, hence these sets are overlapping sets.





#### Complement and universal set

The universal set (if it exists), usually denoted U, is a set of which everything conceivable is a member. In pure set theory, normally sets are the only objects considered (unlike here, where we have also considered numbers, colours and books, for example); in this case U would be the set of all sets. (Non-set objects, where they are allowed, are called 'urelemente' and are discussed below.)

In the presence of a universal set we can define X′, the complement of X, to be $U−X$. X′ contains everything in the universe apart from the elements of X. We could alternatively have defined it as

\[X′ = \{x | \tilde (x\in X)\}\]
and U as the complement of the empty set.

{Equal and Equivalent Sets}

<p>

Difference between equal sets and equivalent sets


*  Consider the sets {A} and {B}
\[ \boldsymbol{A} = \{ 1,2,3,4,5,6 \} \] 
\[ \boldsymbol{B} = \{1,2,3,4,5,6 \} \]

*  {A} and {B} are \textit{{equal}} sets because \textit{{all}} their
elements are precisely the \textit{{same}}.




#### Equal and Equivalent Sets


Difference between equal sets and equivalent sets


*  Consider the sets {C} and {D}
\[ \boldsymbol{C} = \{a,b,c,d,e,f\} \]  \[ \boldsymbol{D} = \{3,4,5,6,7,8\} \]

*  {C} and {D} are \textit{{equivalent}} sets
because the cardinality of both the sets is the same (i.e. 6.)
*  However {C} and {D} are not equal, as they are comprised of different elements.




*  Necessarily all equal sets are equivalent sets.
*  But are equivalent sets equal sets?

*  No, because equivalent sets are sets that have the \textit{{same}} cardinality but equal sets are sets that all
their elements are precisely the \textit{{same}}. 


#### Example:

*  {X}=\{p,q,r\} and {Y}=\{1,2,3\} are equivalent sets 
*  {E} =\{m,n,o,p\}
and {F}=\{m,n,o,p\} are equal and equivalent sets


### Ordered Lists 

If we consider "the songs on my iPod" as a familiar example of a set, then "a playlist on my iPod" is the corresponding example of an ordered list. Key properties of ordered lists include:

*  Order of elements in an ordered list is relevant.
*  Repetition of elements in an ordered list is relevant.


Explicit notion for writing ordered lists is similar to that for sets; however, we use parentheses instead of curly braces. For example:




*  (1,2) is an ordered list that is different than (2,1)
*  (1,1) is an ordered list that is different than (1)

From now on, expressions with parentheses "( , , , )" and expressions with curly braces "{ , , , }" have very distinct meanings!

The length of an ordered list is, intuitively speaking, just like the number of songs in a playlist. For example:



* The length of (1,10) is 2
* The length of (1,1,2,2) is 4
An ordered pair is an ordered list of length two. We will use ordered pairs very often in our study of the Web; we will use longer ordered lists less often. Also, we will never attempt to define the cardinality of an ordered list. Sets have cardinality. Ordered lists have length.



Any element in an ordered list can itself be an ordered list or a set. Any object in a set can be a set or an ordered list. 

For example:
{(1,2),(3,4)} is a set of two elements, each of which is an ordered pair. One of the elements of the set is (1,2) and the other element of the set is (3,4).
({1,2},{3},{2,4}) is an ordered list of sets. The first element of the list is the set {1,2}; the second element of the list is the set {3}; the third element of the list is the set {2,4}.




#### Partitioning of a Set
Partition of a set, say S, is a collection of n disjoint subsets, say $P1,P2 \ldots Pn$  that satisfies the following three conditions :


*  $Pi$ does not contain the empty set.

 $[Pi \neq {\varnothing} for all 0<i\leq n]$
*  The union of the subsets must equal the entire original set.

\[P1 \cup P2 \cup \ldots \cup Pn=S\]
*  The Intersection of any two distinct sets is empty.

\[Pa \cap Pb={\varnothing}, for a\neq b where n\geq a,b\geq 0\]


#### Example

Let $S={a,b,c,d,e,f,g,h}$

*  One probable partitioning is ${a},{b,c,d},{e,f,g,h}$
*  Another probable partitioning is ${a,b},{c,d},{e,f,g,h}$


