
Set Theory - Worksheets {data-navmenu="Section 2"}
==================================

Column {.tabset}
-----------------------------

### Worksheets 1

#### Question 1

Describe the following set by the rules of inclusion method.

a. $\{12,13,14,15,16,17\}$

b. $\{0,5,-5,10,-10,15,-15,.....\}$

c. $\{6,8,10,12,14,16,18\}$
    

<hline>

#### Question 2

Describe the following set by the listing method the set of positive multiples of 3 which are less than 20.


<hline>

#### Question 3 

Describe the following set by the listing method
\[ \{ 2r+1 : r \in Z^{+} and r \leq 5  \} \]

<hline>

#### Question 4 

For each of the following sets, write out the set using the listing method.
Also write down the cardinality of each set.


a.  $\{ 10^m : -2 \leq m \leq 4, m \in \mathbb{Z} \} $

b.   $ \{ \frac{1}{n}: 1 < n < 4, n \in \mathbb{Z} \} $


<hline>

For each of the following sets, write out the set using the listing method.
Also write down the cardinality of each set.


a. $\{ s : s $ is an negative integer $ -10 \leq s \leq 0 \}$

b. $\{ t : t $ is an even number $ 1 \leq t \leq 20 \}$

c. $\{ u : u $ is a prime number $ 1 \leq u \leq 20 \}$

d. $\{ v : v $ is a multiple of 3 $ 1 \leq v \leq 20 \}$

<hline>

#### Question 4
 

 Let $A = \{2n+1 : n \in Z^{+}\}$ be a set of numbers. Describe the set $A$ by the listing method.

<hline>

#### Question 5
 
U = {natural numbers}; $A = \{2, 4, 6, 8, 10\}$; $B = \{1, 3, 6, 7, 8\}$. State whether each of the following is true or false:

a.  $A \subset U$

b.  $B \subseteq A$

c. $\emptyset \subset U$


<hline>

#### Question 6
 
For each of the following sets, write out the set using the listing method.
Also write down the cardinality of each set.

a. $\{ s :  \mbox{ s is an odd integer and } 2 \leq s \leq 10 \}$

b. $\{ 2m :  m \in Z \mbox{ and }5 \leq m \leq 10 \}$

c. $\{ 2^t :  t \in Z \mbox{ and } 0 \leq t \leq 5 \}$


<hline>

#### Question 7

Let $A$ and $B$ be subsets of universal set $U$. Use the membership rule to prove that
\[(A^\prime  \cap B)^\prime = A \cup B^\prime\]
Shade the region corresponding to this set on a Venn Diagram

* Given the universal set $$\mathcal{U} = {1,2,3,4,5,6,7,8,9}$$ and the subsets $A=\{1,3,5,7\}$
$B = \{6,7,8,9\}$ list the set $A^\prime \cap B)^\prime$
* Shade in the following areas on Venn diagrams.


a.  $A^\prime\; \cup\; B$

b.  $A \cap\; B^\prime\;$

c. $(A \cap\; B)^\prime\;$

d. $A^\prime\; \cup\; B^\prime\;$

d. $(A \cup\; B)^\prime\;$

f. $A^\prime\; \cap\; B^\prime\;$


<hline> 

The following sets have been defined using the \textbf{Building Method} of notation. Re-write them by listing \textbf{some} of the elements.

* $\{p | p$ is a capital city, p is in Europe$\}$

* $\{x | x = 2n - 5,$ x and n are natural numbers$\}$

* $\{y | 2y^2 = 50,$ y is an integer$\}$

* $\{z | z = n^3,$ z and n are natural numbers$\}$

Consider the universal set $U$ such that
\[U=\{1,2,3,4,5,6,7,8,9\} \]
and the sets
\[A=\{2,5,7,9\} \]
\[B=\{2,4,6,8,9\} \]


a.  $A-B$

b.  $A \otimes B$

c. $A \cap B$

d. $A \cup B$

d. $A^{c} \cap B^{c}$

f. $A^{c} \cup B^{c}$

<hline> 


* Let A, B be subsets of the universal set $\mathcal{U}$.

Use membership tables to prove De Morgan's Laws.


