Relations and Digraphs {data-navmenu="Relations"}
=====================================



Column {.tabset}
-------------------------------------------------

#### Digraphs and Relations

### Relations

* A relation $R$ from a set A to a set B is a subset of the
***cartesian product*** A x B. 
* Thus R is a set of \textbf{ordered pairs} where
the first element comes from A and the second element comes
from B i.e. $(a, b)$

* If $(a, b) \in R$ we say that $a$ is related to $b$ and write $aRb$.
* If $(a, b) \notin R$, we say that $a$ is not related to $b$ and write $aRb$. CHECK
* If $R$ is a relation from a set $A$ to itself then we say that ``$R$ is a relation
on $A$".



### Relations 

Let R be an equivalence relation defined on a set S and let x 2 S. 
Then the equivalence class of x is the subset of S containing all
elements of S which are related to x. 

We denote this by [x]. Thus
\[[x] = {y 2 S : yRx}\].


#### Types of Relations


*  Antisymmetric
*  Symmetric
*  Reflexive 
*  Transitive

#### Theorem 1.3 
Let R be an equivalence relation on a set S. Then:
\begin{itemize}
*  The set of distinct equivalence classes of R on S is a partition of S.
*  Two elements of S are related if and only if they belong to the same equivalence
class.



If S is a set, we will use the symbol “R” to denote either an abstract relation or a speci?c
relation for which there is no standard notation. For a, b \in S we will write a R b, not
$(a, b) \in R$, to indicate that a and b are related.

 Definition 1: Let R be a relation of a set S. We say that R is re?exive provided for all
a \in S, a R a.

 Definition 2: Let R be a relation of a set S. We say that R is symmetric provided for
all $a, b \in S$, if a R b then b R a.

*  Definition 3: Let R be a relation of a set S. We say that R is transitive provided for
all a, b, c \in S, if a R b and b R c then a R c.

#### Worked Example 
For a, b \in Z define a R b to mean that a divides b.

\begin{itemize}
* [(a)] State whether or not R is reflexive.
* [(b)] State whether or not R is symmetric.
* [(c)] State whether or not R is transitive.
\end{itemize}
Solution: 


* [(a)]  Since 0 does not divide 0, therefore R is not re?exive.
* [(b)] 2 divides 4 so 2 R 4. But 4 does not divide 2, so 4 R 2. Thus, R is not symmetric.
* [(c)]  To see that R is transitive, let a, b, c be integers. Suppose that $a R b$ and $b R c$. Thus,
a divides b and b divides c so there exist integers k and l such that b = ak and c = bl. This
gives c = bl = (ak)l = a(kl). Therefore, a divides c so a R c


<hline>

#### Anti-Symmetfric Relations

We say that a relation R on a set S is anti-symmetric if for
all x, y 2 S such that xRy and yRx, we have $x = y$. 

Thus R is ***anti-symmetric*** if and only if the relationship digraph of R has no directed cycles of length two.


### Videos 

<h4>Videos</h4>

* < a href = ="https://www.youtube.com/watch?v=/4vSr6q5Nxqc"> Digraphs and Relations</a>

*  < a href = ="https://www.youtube.com/watch?v=/dHzu897SdDA">  Cartesian Products</a>

*  < a href = ="https://www.youtube.com/watch?v=/4vSr6q5Nxqc">  Digraphs and Relations -Example</a>

* < a href = ="https://www.youtube.com/watch?v=/eZIEc1O0W1w"> Relations Example 2</a>

*  < a href = ="https://www.youtube.com/watch?v=/dHzu897SdDA">  Cartesian </a>

*  < a href = ="https://www.youtube.com/watch?v=/4vSr6q5Nxqc">  Digraphs and Relations -Example</a>

* < a href = ="https://www.youtube.com/watch?v=/rG8mhlqnkr0">  Relations -Example</a>

*  < a href = ="https://www.youtube.com/watch?v=/_QTKlTJYKRA">  Transitive Relations</a>

*  < a href = ="https://www.youtube.com/watch?v=/A08P9ZJsLOs">  Relations -Example</a>
