Sequences and Series {data-navmenu="Section 5"}
=====================================

Column {.tabset}
-------------------------------------------------

### Introduction 

* Sequences - what are sequences?
* Arithmetic Progressions
* Geometric Progressions
* Recurrences Relationships (Fibonacci Sequence)

### Videos

*  Part 1 : Sequences
*  Part 2 : Proof by Induction
*  Part 3 : Series and the Sigma Notation


* <a href="https://www.youtube.com/watch?v=/FsnDh03YYVQ"> Sequences and Series - Sequences</a>
* <a href="https://www.youtube.com/watch?v=/puPz1kBzoi4"> Sequences and Series : Basic Sequences	</a>
* <a href="https://www.youtube.com/watch?v=/puPz1kBzoi4">Sequences and Series : Basic Sequences	</a>
* <a href="https://www.youtube.com/watch?v=/wGzpAfUTJTw"> Arithmetic Progressions (Sequences and Series)</a>
* <a href="https://www.youtube.com/watch?v=/sAm0PHazpvQ"> Sequences and Series - Geometric Series</a>
* <a href="https://www.youtube.com/watch?v=/OvHeYH9mNkA">Geometric Series (Sequence and Series)</a>
    
 
* <a href="https://www.youtube.com/watch?v=/4yQaMo9zqCs"> Series Part 1</a>
* <a href="https://www.youtube.com/watch?v=/hoodEvYAGxQ"> Sequences 2001 basic sequences</a>
* <a href="https://www.youtube.com/watch?v=/oZgnNIUZSVA">Sequences and Series 2002 evaluating a series</a>
      
* <a href="https://www.youtube.com/watch?v=/mUws2ruOP9k"> Sequences and Series 2001 summations</a>
* <a href="https://www.youtube.com/watch?v=/BCzU5smvhMY"> Recurrence Relations 2004</a>

*  <a href="http://youtu.be/r5SiDTplMwI">Sigma Notation</a> [6.49]
*  <a title="Sequence Expression" href="http://youtu.be/vLAorai793I" >Determining Sequence Expressions</a>
*  <a title="Finite Series" href="http://youtu.be/NnuAIuvf73U" >Finite Series</a> :  Summation of a sequence.


* <a href="https://www.youtube.com/watch?v=/D8zZ7nr80r8">    Sigma Notation</a>
* <a href="https://www.youtube.com/watch?v=/lwjpA522bnY">    Finite Series</a>

    
* <a href="https://www.youtube.com/watch?v=/NhUBAYcfY_A">Evaluating the Sum of a Series</a>
  
* <a href="https://www.youtube.com/watch?v=/sAm0PHazpvQ">Geometric Series </a>

* <a href="https://www.youtube.com/watch?v=/XVyyGuMtyPo">Geometric Summation Exercise</a>
 
  
  


#### Sigma Notation and Finite Series

*  <a href="https://www.youtube.com/watch?v=O8y3OInkTsg" >Sigma Notation</a> (6:49 Minutes)
*  Finite Series – <a title="Sequences and Series : Finite Series " href="https://www.youtube.com/watch?v=HQ-nWl6Xfn4" >HERE</a> (4:40 Minutes)
*  Evaluating the Sum of a Series – <a href="http://youtu.be/NhUBAYcfY_A" >HERE</a> ( 3:12 Minutes)

#### Geometric Series

*  Geometric Series - <a href="https://www.youtube.com/watch?v=sAm0PHazpvQ" >HERE</a>  - [14:41]
*  <a href="https://www.youtube.com/watch?v=XVyyGuMtyPo">Geometric Summation Exercise</a>



#### Series 

*  Evaluating the Sum of a Series – <a href="http://youtu.be/NhUBAYcfY_A" >HERE</a> ( 3:12 Minutes)


		
#### Proof by Induction
  
*  <a href="https://www.youtube.com/watch?v=VbO3eX1YKiM">Proof By Induction Example </a>
	

    

#### Sequences

*  Sequences – <a href="http://youtu.be/dZpq0JV_5vI" >HERE</a>
*  Sequences Value Determination – <a href="http://youtu.be/Q8AeZu2g6nk" >HERE</a> (2:24 Minutes)
*  Arithmetic Progressions - <a href="https://www.youtube.com/watch?v=wGzpAfUTJTw" >HERE </a> (7:00)



*  Sequences – <a href="http://youtu.be/dZpq0JV_5vI" >HERE</a>
*  Sequences Value Determination – <a href="http://youtu.be/Q8AeZu2g6nk" >HERE</a> (2:24 Minutes)
*  Arithmetic Progressions - <a href="https://www.youtube.com/watch?v=wGzpAfUTJTw" >HERE </a> (7:00)


#### Proof by Induction

	<li class="sharedaddy sd-like-enabled sd-sharing-enabled">Simple Example - <a href="https://youtu.be/Jqd_Mvpxsbo" >HERE</a> [ 6:14 ]


#### Series 

*  Sigma Notation - <a href="https://youtu.be/D8zZ7nr80r8" >Here</a> [6:49]
*  Finite Series – <a title="Sequences and Series : Finite Series " href="http://youtu.be/lwjpA522bnY" >HERE</a> (4:40 Minutes)
*  Evaluating the Sum of a Series – <a href="http://youtu.be/NhUBAYcfY_A" >HERE</a> ( 3:12 Minutes)
*  Geometric Series - <a href="https://www.youtube.com/watch?v=sAm0PHazpvQ" >HERE</a>  - [14:41]
*  <a href="https://www.youtube.com/watch?v=XVyyGuMtyPo">Geometric Summation Exercise</a>




#### Sequences and Series

*  Sequences - <a href="http://Sequences" >HERE</a>
*  Introduction to Sequences and Series – <a href="https://youtu.be/z2m2fscysX0" >HERE</a>
*  Sequences Value Determination – <a href="https://www.youtube.com/watch?v=4pdtlxc2UKs" >HERE</a> (2:24 Minutes)
*  Arithmetic Progressions - <a href="https://www.youtube.com/watch?v=wGzpAfUTJTw" >HERE </a> (7:00 Minutes)

### Telescoping Series

	
#### Videos

*  <a title="Evaluating Sequence Values" href="https://www.youtube.com/watch?v=GcVEi0gP820" >Introduction to </a><a href="https://www.youtube.com/watch?v=wQ4_kSZAkAQ">Sequences – Part 1</a> [4:09]
*  <a href="https://www.youtube.com/watch?v=Mj0Z1ts8U0k">Introduction to Sequences – Part 3</a> [8:27]
*  <a title="Evaluating Sequence Values" href="https://www.youtube.com/watch?v=GcVEi0gP820" >Evaluating Sequence Values</a>

*  Exam Question <a href="https://www.youtube.com/watch?v=TZ_k798VNdk">Sequences and Series 2003 proof by induction</a>


<strong>Telescoping Series</strong>

*  <a href="https://www.youtube.com/watch?v=CcYnFbo8-xw">Telescoping Series (Lecture)</a>
*  Telescoping Series - Worked Example - <a href="http://Telescoping%20Series (Lecture)" >HERE</a>
