Finite Series {data-navmenu="Section 5"}
=====================================

Column {.tabset}
-------------------------------------------------


### Finite Series and Sigma Notation
Mathematical notation uses a symbol that compactly represents summation of many similar terms: the summation symbol, $\sum$, an enlarged form of the upright capital Greek letter *Sigma*. 

This is defined as:
\[\sum_{i=m}^n a_i = a_m + a_{m+1} + a_{m+2} +\cdots+ a_{n-1} + a_n. \]
Where, i represents the index of summation; ai is an indexed variable representing each successive term in the series; m is the lower bound of summation, and n is the upper bound of summation. The "i = m" under the summation symbol means that the index i starts out equal to m. The index, i, is incremented by 1 for each successive term, stopping when i = n.
Here is an example showing the summation of exponential terms (all terms to the power of 2):
\[\sum_{i=3}^6 i^2 = 3^2+4^2+5^2+6^2 = 86.\]
Informal writing sometimes omits the definition of the index and bounds of summation when these are clear from context, as in:
\[\sum a_i^2 = \sum_{i=1}^n a_i^2.\]


#### Three Important Summation Identities
(index term = i , Number of terms = n }


*  Identity 1
\[ \sum^{i=n}_{i=1} 1 = n \]
*  Identity 2  
\[ \sum^{i=n}_{i=1} i = \frac{n(n+1)}{2} \]
*  Identity 3 
\[ \sum^{i=n}_{i=1} i^2 = \frac{(2n+1)(n+1)(n)}{6} \]


### Partitioning of Summations 


For some integers $m$ and $n$, with $m<n$.

\[ \sum^{i=n}_{i=1} u_{i} = \sum^{i=m}_{i=1} u_{i} + \sum^{i=n}_{i=m+1} u_{i}\]

Suppose $n=100$ and $m=50$

\[ \sum^{i=100}_{i=1} u_{i} = \sum^{i=50}_{i=1} u_{i} + \sum^{i=100}_{i=51} u_{i}\]

\textbf{Example}
Evaluate the following expression:
\[ \sum^{i=100}_{i=51} (i+1) \]


***Step 1*** Evaluate this expression using the identities (notice the lower bound)
\[ \sum^{i=100}_{i=1} (i+1) \]
***Step 2*** From the outcome of step 1, subtract the following
\[ \sum^{i=50}_{i=1} (i+1) \]




<h5>Step 1</h5> Evaluate the following expression using the identities. In this step $n=100$
\[ \sum^{i=100}_{i=1} (i+1)  = \sum^{i=100}_{i=1} i  +  \sum^{i=100}_{i=1} 1  \]

1. First term \[\sum^{i=100}_{i=1} i  = \frac{100\times(100+1)}{2}  = 5050\]
2. Second term \[ \sum^{i=100}_{i=1} i  =  100\]


\[ \sum^{i=100}_{i=1} (i+1)  = 5050 + 100 = 5150 \]




<h5>Step 2</h5>
Evaluate the following expression using the identities. In this step $n=50$
\[ \sum^{i=50}_{i=1} (i+1)  = \sum^{i=50}_{i=1} i  +  \sum^{i=50}_{i=1} 1  \]

1. First term \[\sum^{i=50}_{i=1} i  = \frac{50\times(50+1)}{2}  = 1275\]
2. Second term \[ \sum^{i=50}_{i=1} i  =  50\]


\[ \sum^{i=50}_{i=1} (i+1)  = 1275 + 50 = 1325 \]


\[ \sum^{i=100}_{i=51} (i+1) = \sum^{i=100}_{i=1} (i+1)  - \sum^{i=50}_{i=1}(i+1)   \]

\[ \sum^{i=100}_{i=51} (i+1)  = 5150 - 1325 =\boldsymbol{3825} \]
